/** Bundled mini crosswords — what the game plays when neither model could
 * fill a grid, and the only thing that works with no signal at all.
 *
 * The grids are generated, the clues are not. Run
 * `npx tsx scripts/buildWordPuzzles.ts` to produce new grids from the
 * vetted pool in scripts/wordPool.ts; every answer in a new grid then needs
 * a line in CLUES below before it can ship, and the engine refuses to build
 * a puzzle whose answers aren't all clued rather than showing a blank clue.
 *
 * Grids are stored as rows and the entries derived from the shared slot
 * pattern at load time (see miniCrosswordEngine), so the clue for a word
 * lives in exactly one place however many grids use it. */

export const MINI_GRIDS: string[][] = [
  ['MAT##', 'ALERT', 'STAIR', 'HORSE', '##SEE'],
  ['CUT##', 'ASIDE', 'MEDIA', 'PRESS', '##SHE'],
  ['APE##', 'GUARD', 'ERROR', 'DENSE', '##SEW'],
  ['PET##', 'ACRES', 'WHALE', 'NOISE', '##TEN'],
  ['RIM##', 'AROMA', 'NOVEL', 'KNEEL', '##STY'],
  ['SAP##', 'LIONS', 'IDEAL', 'TEMPO', '##SET'],
  ['SUN##', 'CREPT', 'AGREE', 'NEVER', '##ELM'],
  ['SHE##', 'CIVIC', 'ARENA', 'RENTS', '##TOE'],
  ['SAW##', 'PLAIN', 'ASIDE', 'NOTES', '##SAT'],
  ['TOP##', 'EARNS', 'STOOL', 'THOSE', '##FED'],
  ['RAN##', 'ALARM', 'MOVIE', 'PEACE', '##LET'],
  ['BUT##', 'ASHES', 'NERVE', 'GREEN', '##END'],
  ['SAD##', 'CLAIM', 'ASIDE', 'ROLLS', '##YES'],
  ['EAT##', 'ALERT', 'COLOR', 'HELLO', '##SET'],
];

export const CLUES: Record<string, string> = {
  ACRES: 'Land measures',
  AGED: 'Got older',
  AGREE: 'Say yes together',
  AIDE: 'Helper to someone important',
  ALARM: 'It goes off at seven',
  ALERT: 'Wide awake and watching',
  ALLY: 'Friend on your side',
  ALOE: 'Plant for a sunburn',
  ALSO: 'As well',
  ALTO: 'Voice below soprano',
  APE: 'Chimp or gorilla',
  ARENA: 'Big sports venue',
  AROMA: 'Smell from the kitchen',
  ASHES: "What's left after a fire",
  ASIDE: 'Moved out of the way',
  BANG: 'Loud sudden noise',
  BUT: 'However',
  CAMP: 'Tents and a fire',
  CASE: 'Box, or a mystery',
  CIVIC: 'To do with the town',
  CLAIM: "Say it's yours",
  COLOR: 'Red, blue or yellow',
  CREPT: 'Moved very quietly',
  CUT: 'Slice with scissors',
  DAILY: 'Every single day',
  DENSE: 'Packed very tightly',
  DISH: 'Plate, or a recipe',
  DREW: 'Made a picture',
  EACH: 'Every one',
  EARNS: 'Gets paid for work',
  EASE: 'Comfort, with no effort',
  EAT: 'Have dinner',
  ECHO: 'It comes back to you',
  ELM: 'Tall shady tree',
  ELSE: 'Otherwise',
  END: 'The finish',
  ERROR: 'A mistake',
  EVEN: 'Flat, or not odd',
  EVENT: 'Something happening',
  FED: 'Gave dinner to',
  GREEN: 'Colour of grass',
  GUARD: 'Keep watch over',
  HELLO: 'Greeting at the door',
  HIRE: 'Take someone on',
  HORSE: 'It trots and neighs',
  IDEA: 'A thought that strikes',
  IDEAL: 'Perfect for the job',
  IDLE: 'Doing nothing at all',
  INTO: 'Heading inside',
  IRON: 'Metal, or press shirts',
  KNEEL: 'Go down on one knee',
  LET: 'Allow',
  LIONS: 'Pride on the plains',
  MASH: 'Potatoes, squashed',
  MAT: 'Wipe your feet here',
  MEDIA: 'News and TV',
  MEET: 'Get together',
  MESS: 'Untidy state',
  MOVES: 'Shifts about',
  MOVIE: 'Popcorn and a screen',
  NAPE: 'Back of the neck',
  NAVAL: 'To do with the fleet',
  NERVE: 'Courage under pressure',
  NEST: 'Twiggy bird home',
  NEVER: 'Not once',
  NOISE: 'A racket',
  NOSE: 'It smells',
  NOTES: 'Jottings, or music',
  NOVEL: 'A book, or brand new',
  OATH: 'Solemn promise',
  PAWN: 'Smallest chess piece',
  PEACE: 'Quiet, and no war',
  PEEL: 'Take the skin off',
  PET: 'Cat or dog at home',
  PLAIN: 'Simple, or flat land',
  POEMS: 'Verses',
  PRESS: 'Push, or the news',
  PROOF: "It shows it's true",
  PURE: 'Nothing mixed in',
  RAMP: 'Slope up to a door',
  RAN: 'Went quickly',
  RANK: 'Position in an order',
  RENTS: 'Pays to use',
  RICE: 'Grains in a bowl',
  RIM: 'Edge of a cup',
  RISE: 'Go up',
  ROLE: 'Part in a play',
  ROLLS: 'Bread, or tumbles over',
  ROSE: 'Thorny flower',
  SAD: 'Feeling blue',
  SAP: 'Sticky juice from a trunk',
  SAT: 'Took a seat',
  SAW: 'Cutting tool, or spotted',
  SCAN: 'Look over quickly',
  SCAR: 'Mark left by a cut',
  SEE: 'Look at',
  SEEN: 'Spotted',
  SEND: 'Post it off',
  SET: 'Group that goes together',
  SEW: 'Work with a needle',
  SHE: 'That girl',
  SLED: 'Downhill in the snow',
  SLIT: 'Narrow cut',
  SLOT: 'Where the coin goes',
  SPAN: 'Reach across',
  STAIR: 'One step of many',
  STOOL: 'Seat with no back',
  STY: 'Home for pigs',
  SUN: 'It rises in the east',
  TEARS: 'Crying drops',
  TELLS: 'Says to someone',
  TEMPO: 'Speed of the music',
  TEN: 'Fingers on two hands',
  TERM: 'School stretch',
  TEST: 'Exam',
  THOSE: 'Not these',
  THREE: 'Before four',
  TIDES: 'They come in and go out',
  TOE: 'Ten on your feet',
  TOP: 'Highest point',
  TRAIT: 'Part of a character',
  TREE: 'Trunk and branches',
  TROT: 'Faster than a walk',
  URGE: 'A strong wish',
  USER: 'Person on the app',
  WAITS: 'Stands in line',
  WHALE: 'Biggest one in the sea',
  YES: 'Agreed',
};
