import type { WordSearchPuzzle } from './firestoreWordSearch';

/** Fifty ready-made word searches, bundled with the app.
 *
 * These exist for one situation: the player has no connection, so no
 * Cloud Function can be reached and no topic can be generated. Rather than
 * a dead end, they get offered one of these.
 *
 * The grids are baked, not built at runtime — produced by running the same
 * deterministic placer the server uses over these word lists, so the client
 * carries no copy of that algorithm and the layouts are fixed and
 * reviewable. Ids are prefixed 'local-' so every lookup can tell a bundled
 * puzzle from a Firestore one without a separate flag.
 *
 * Generated file — see the note in wordSearchOffline.ts before editing. */
export const OFFLINE_PUZZLES: WordSearchPuzzle[] = [
  {
    id: 'local-farm-animals',
    topic: "Farm Animals",
    topicSlug: 'farm-animals',
    difficulty: 'hard',
    size: 10,
    grid: ["OIOWUOYAYK","KHORSENAET","TCSEKGEAKB","FRCRCOKENM","PEUOUOCOOA","LTOKDSIEDL","YSDHIEHUCC","UOEFLACEAY","GOATOKOPEG","KRPONYEGIP"],
    words: [{"word":"CHICKEN","row":7,"col":6,"dRow":-1,"dCol":0},{"word":"ROOSTER","row":9,"col":1,"dRow":-1,"dCol":0},{"word":"DONKEY","row":5,"col":8,"dRow":-1,"dCol":0},{"word":"TURKEY","row":5,"col":1,"dRow":-1,"dCol":1},{"word":"HORSE","row":1,"col":1,"dRow":0,"dCol":1},{"word":"SHEEP","row":5,"col":5,"dRow":1,"dCol":1},{"word":"GOOSE","row":2,"col":5,"dRow":1,"dCol":0},{"word":"GOAT","row":8,"col":0,"dRow":0,"dCol":1},{"word":"DUCK","row":5,"col":4,"dRow":-1,"dCol":0},{"word":"LAMB","row":5,"col":9,"dRow":-1,"dCol":0},{"word":"CALF","row":7,"col":6,"dRow":0,"dCol":-1},{"word":"PONY","row":9,"col":2,"dRow":0,"dCol":1},{"word":"COW","row":2,"col":1,"dRow":-1,"dCol":1},{"word":"PIG","row":9,"col":9,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-jungle-animals',
    topic: "Jungle Animals",
    topicSlug: 'jungle-animals',
    difficulty: 'hard',
    size: 10,
    grid: ["OTKRAUGAJG","REGITYGTLN","GORFSETAAR","LEPGMLYSUE","IOAGOEOMRT","ZRRSKRETGA","AERNNLIRHE","RTOUCANLLT","DMTGECKOLN","REBEETLERA"],
    words: [{"word":"ANTEATER","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"GORILLA","row":3,"col":3,"dRow":1,"dCol":1},{"word":"MONKEY","row":8,"col":1,"dRow":-1,"dCol":1},{"word":"PARROT","row":3,"col":2,"dRow":1,"dCol":0},{"word":"JAGUAR","row":0,"col":8,"dRow":0,"dCol":-1},{"word":"TOUCAN","row":7,"col":1,"dRow":0,"dCol":1},{"word":"LIZARD","row":3,"col":0,"dRow":1,"dCol":0},{"word":"BEETLE","row":9,"col":2,"dRow":0,"dCol":1},{"word":"TIGER","row":1,"col":4,"dRow":0,"dCol":-1},{"word":"SNAKE","row":5,"col":3,"dRow":1,"dCol":1},{"word":"SLOTH","row":2,"col":4,"dRow":1,"dCol":1},{"word":"LEMUR","row":6,"col":5,"dRow":-1,"dCol":1},{"word":"GECKO","row":8,"col":3,"dRow":0,"dCol":1},{"word":"FROG","row":2,"col":3,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-ocean-life',
    topic: "Ocean Life",
    topicSlug: 'ocean-life',
    difficulty: 'hard',
    size: 10,
    grid: ["JDLCRABTET","EDOCTOPUSW","LFBLFPSRBH","LRSEPEQTJA","YKTECHULRL","FRERICIEEE","IARLDODNTS","SHLSTRFRSY","HSIFRATSYS","LAESSLTSOS"],
    words: [{"word":"JELLYFISH","row":0,"col":0,"dRow":1,"dCol":0},{"word":"STARFISH","row":8,"col":7,"dRow":0,"dCol":-1},{"word":"DOLPHIN","row":0,"col":1,"dRow":1,"dCol":1},{"word":"OCTOPUS","row":1,"col":2,"dRow":0,"dCol":1},{"word":"LOBSTER","row":0,"col":2,"dRow":1,"dCol":0},{"word":"TURTLE","row":0,"col":7,"dRow":1,"dCol":0},{"word":"OYSTER","row":9,"col":8,"dRow":-1,"dCol":0},{"word":"WHALE","row":1,"col":9,"dRow":1,"dCol":0},{"word":"SHARK","row":8,"col":1,"dRow":-1,"dCol":0},{"word":"CORAL","row":5,"col":5,"dRow":1,"dCol":0},{"word":"SQUID","row":2,"col":6,"dRow":1,"dCol":0},{"word":"CRAB","row":0,"col":3,"dRow":0,"dCol":1},{"word":"SEAL","row":9,"col":3,"dRow":0,"dCol":-1},{"word":"EEL","row":4,"col":3,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-birds',
    topic: "Birds",
    topicSlug: 'birds',
    difficulty: 'hard',
    size: 10,
    grid: ["IPIGEONERW","MNESLCPBWF","NALNPUFFIN","OFGHGALWOI","ORAPEURWCB","IBELIRIRRO","ILEPCEONOR","BNORSOPNWW","NFINCHNAWS","NEFHAOHINW"],
    words: [{"word":"PENGUIN","row":0,"col":1,"dRow":1,"dCol":1},{"word":"SPARROW","row":1,"col":3,"dRow":1,"dCol":1},{"word":"PIGEON","row":0,"col":1,"dRow":0,"dCol":1},{"word":"FALCON","row":3,"col":1,"dRow":1,"dCol":1},{"word":"MAGPIE","row":1,"col":0,"dRow":1,"dCol":1},{"word":"PUFFIN","row":2,"col":4,"dRow":0,"dCol":1},{"word":"ROBIN","row":6,"col":9,"dRow":-1,"dCol":0},{"word":"EAGLE","row":5,"col":2,"dRow":-1,"dCol":0},{"word":"HERON","row":3,"col":3,"dRow":1,"dCol":1},{"word":"FINCH","row":8,"col":1,"dRow":0,"dCol":1},{"word":"SWAN","row":8,"col":9,"dRow":0,"dCol":-1},{"word":"CROW","row":4,"col":8,"dRow":1,"dCol":0},{"word":"WREN","row":0,"col":9,"dRow":0,"dCol":-1},{"word":"OWL","row":3,"col":8,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-bugs-and-insects',
    topic: "Bugs and Insects",
    topicSlug: 'bugs-and-insects',
    difficulty: 'hard',
    size: 10,
    grid: ["MANTISRCAT","IREDIPSTET","DEDIHWHMAL","GCIITEOPRB","ERHPOERAWA","EIPMMVNSII","BCAMDIEEGM","DKTNELTEEB","KESITMPSAW","ITSUCOLLSC"],
    words: [{"word":"CRICKET","row":3,"col":1,"dRow":1,"dCol":0},{"word":"BEETLE","row":7,"col":9,"dRow":0,"dCol":-1},{"word":"SPIDER","row":1,"col":6,"dRow":0,"dCol":-1},{"word":"LOCUST","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"EARWIG","row":1,"col":8,"dRow":1,"dCol":0},{"word":"WEEVIL","row":2,"col":5,"dRow":1,"dCol":0},{"word":"MANTIS","row":0,"col":0,"dRow":0,"dCol":1},{"word":"HORNET","row":2,"col":6,"dRow":1,"dCol":0},{"word":"APHID","row":6,"col":2,"dRow":-1,"dCol":0},{"word":"MIDGE","row":0,"col":0,"dRow":1,"dCol":0},{"word":"WASP","row":8,"col":9,"dRow":0,"dCol":-1},{"word":"MOTH","row":5,"col":4,"dRow":-1,"dCol":0},{"word":"ANT","row":6,"col":2,"dRow":1,"dCol":1},{"word":"BEE","row":6,"col":0,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-breakfast',
    topic: "Breakfast",
    topicSlug: 'breakfast',
    difficulty: 'hard',
    size: 10,
    grid: ["ELFFAWLYEA","ECIUJOEJFO","FAPYENEYKL","FELOOKAUSE","OCEHAGOTGT","CBACONUEGA","EKNLLAEREC","TALEGABKTL","PTOASTAOBC","ILSEUMAJGI"],
    words: [{"word":"PANCAKE","row":8,"col":0,"dRow":-1,"dCol":1},{"word":"CEREAL","row":6,"col":9,"dRow":0,"dCol":-1},{"word":"WAFFLE","row":0,"col":5,"dRow":0,"dCol":-1},{"word":"YOGURT","row":2,"col":3,"dRow":1,"dCol":1},{"word":"COFFEE","row":5,"col":0,"dRow":-1,"dCol":0},{"word":"MUESLI","row":9,"col":5,"dRow":0,"dCol":-1},{"word":"TOAST","row":8,"col":1,"dRow":0,"dCol":1},{"word":"BACON","row":5,"col":1,"dRow":0,"dCol":1},{"word":"JUICE","row":1,"col":4,"dRow":0,"dCol":-1},{"word":"HONEY","row":4,"col":3,"dRow":-1,"dCol":1},{"word":"BAGEL","row":7,"col":6,"dRow":0,"dCol":-1},{"word":"EGGS","row":6,"col":8,"dRow":-1,"dCol":0},{"word":"OATS","row":8,"col":7,"dRow":0,"dCol":-1},{"word":"JAM","row":9,"col":7,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-fruit',
    topic: "Fruit",
    topicSlug: 'fruit',
    difficulty: 'hard',
    size: 10,
    grid: ["HMRNNOMELA","CMELBANANA","ATCOGNAMEE","EOPPENOLEM","PCEPMIPYRI","OIAIRPLREL","CRRWAAURHP","GPGIFAMEMI","LAOKFENHPA","IGIMEENCBA"],
    words: [{"word":"APRICOT","row":8,"col":1,"dRow":-1,"dCol":0},{"word":"BANANA","row":1,"col":4,"dRow":0,"dCol":1},{"word":"CHERRY","row":9,"col":7,"dRow":-1,"dCol":0},{"word":"APPLE","row":6,"col":4,"dRow":-1,"dCol":1},{"word":"GRAPE","row":7,"col":0,"dRow":-1,"dCol":1},{"word":"MANGO","row":2,"col":7,"dRow":0,"dCol":-1},{"word":"PEACH","row":4,"col":0,"dRow":-1,"dCol":0},{"word":"LEMON","row":0,"col":8,"dRow":0,"dCol":-1},{"word":"MELON","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"PLUM","row":4,"col":6,"dRow":1,"dCol":0},{"word":"PEAR","row":3,"col":2,"dRow":1,"dCol":0},{"word":"KIWI","row":8,"col":3,"dRow":-1,"dCol":0},{"word":"LIME","row":5,"col":9,"dRow":-1,"dCol":0},{"word":"FIG","row":7,"col":4,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-vegetables',
    topic: "Vegetables",
    topicSlug: 'vegetables',
    difficulty: 'hard',
    size: 10,
    grid: ["WOECKONION","PADIOKALEA","CABBAGEESE","AAORDWBEPP","WARNOBKKII","CTURNIPINN","AARSOAYEAS","EAOTATOPCR","MNLEDEWSHA","YRELECNEAP"],
    words: [{"word":"SPINACH","row":2,"col":8,"dRow":1,"dCol":0},{"word":"CABBAGE","row":2,"col":0,"dRow":0,"dCol":1},{"word":"PARSNIP","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"CARROT","row":2,"col":0,"dRow":1,"dCol":1},{"word":"POTATO","row":7,"col":7,"dRow":0,"dCol":-1},{"word":"TURNIP","row":5,"col":1,"dRow":0,"dCol":1},{"word":"MARROW","row":8,"col":0,"dRow":-1,"dCol":1},{"word":"CELERY","row":9,"col":5,"dRow":0,"dCol":-1},{"word":"ONION","row":0,"col":5,"dRow":0,"dCol":1},{"word":"SWEDE","row":8,"col":7,"dRow":0,"dCol":-1},{"word":"BEAN","row":3,"col":6,"dRow":-1,"dCol":0},{"word":"LEEK","row":1,"col":7,"dRow":1,"dCol":0},{"word":"KALE","row":1,"col":5,"dRow":0,"dCol":1},{"word":"PEA","row":3,"col":9,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-baking',
    topic: "Baking",
    topicSlug: 'baking',
    difficulty: 'hard',
    size: 10,
    grid: ["RNIPASTRYP","UGAGVPEESW","ONSUCTIMPH","LIFPTIDINI","FCEUOSOTOS","IIBYTNUORK","CMGIONGGPO","IYEASTHEAS","DOVENGIIRR","LSENOCSNRR"],
    words: [{"word":"BUTTER","row":5,"col":2,"dRow":-1,"dCol":1},{"word":"SPONGE","row":2,"col":2,"dRow":1,"dCol":1},{"word":"PASTRY","row":0,"col":3,"dRow":0,"dCol":1},{"word":"FLOUR","row":4,"col":0,"dRow":-1,"dCol":0},{"word":"SUGAR","row":4,"col":5,"dRow":1,"dCol":1},{"word":"YEAST","row":7,"col":1,"dRow":0,"dCol":1},{"word":"DOUGH","row":3,"col":6,"dRow":1,"dCol":0},{"word":"WHISK","row":1,"col":9,"dRow":1,"dCol":0},{"word":"ICING","row":5,"col":1,"dRow":-1,"dCol":0},{"word":"SCONE","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"APRON","row":7,"col":8,"dRow":-1,"dCol":0},{"word":"TIMER","row":4,"col":7,"dRow":-1,"dCol":0},{"word":"OVEN","row":8,"col":1,"dRow":0,"dCol":1},{"word":"TIN","row":7,"col":5,"dRow":1,"dCol":1}],
  },
  {
    id: 'local-pizza-toppings',
    topic: "Pizza Toppings",
    topicSlug: 'pizza-toppings',
    difficulty: 'hard',
    size: 10,
    grid: ["CHMOSPANUT","AOAPPEVILO","ERRMMMHPIM","SPINACHNSA","HOGARLICAT","MUSHROOMBO","BEREPPEPAV","IVESEEHCCH","NNONNOINOO","CHILLITONO"],
    words: [{"word":"MUSHROOM","row":5,"col":0,"dRow":0,"dCol":1},{"word":"SPINACH","row":3,"col":0,"dRow":0,"dCol":1},{"word":"CHEESE","row":7,"col":7,"dRow":0,"dCol":-1},{"word":"TOMATO","row":0,"col":9,"dRow":1,"dCol":0},{"word":"PEPPER","row":6,"col":7,"dRow":0,"dCol":-1},{"word":"CHILLI","row":9,"col":0,"dRow":0,"dCol":1},{"word":"GARLIC","row":4,"col":2,"dRow":0,"dCol":1},{"word":"OLIVE","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"BASIL","row":5,"col":8,"dRow":-1,"dCol":0},{"word":"ONION","row":8,"col":8,"dRow":0,"dCol":-1},{"word":"BACON","row":5,"col":8,"dRow":1,"dCol":0},{"word":"CORN","row":0,"col":0,"dRow":1,"dCol":1},{"word":"TUNA","row":0,"col":9,"dRow":0,"dCol":-1},{"word":"HAM","row":0,"col":1,"dRow":1,"dCol":1}],
  },
  {
    id: 'local-weather',
    topic: "Weather",
    topicSlug: 'weather',
    difficulty: 'hard',
    size: 10,
    grid: ["HGOGURRURY","SWRADEALYD","ERELZZIRDE","ALNERANWNS","YYESHIEUIU","TRNESNOWWN","BATHUNDERN","WOBNIARARY","GNULLDUOLC","GOFROSTORM"],
    words: [{"word":"THUNDER","row":6,"col":2,"dRow":0,"dCol":1},{"word":"DRIZZLE","row":2,"col":8,"dRow":0,"dCol":-1},{"word":"RAINBOW","row":7,"col":6,"dRow":0,"dCol":-1},{"word":"BREEZE","row":6,"col":0,"dRow":-1,"dCol":1},{"word":"CLOUD","row":8,"col":9,"dRow":0,"dCol":-1},{"word":"STORM","row":9,"col":5,"dRow":0,"dCol":1},{"word":"FROST","row":9,"col":2,"dRow":0,"dCol":1},{"word":"SUNNY","row":3,"col":9,"dRow":1,"dCol":0},{"word":"WINDY","row":5,"col":8,"dRow":-1,"dCol":0},{"word":"RAIN","row":0,"col":6,"dRow":1,"dCol":0},{"word":"SNOW","row":5,"col":4,"dRow":0,"dCol":1},{"word":"HAIL","row":4,"col":4,"dRow":-1,"dCol":1},{"word":"GALE","row":0,"col":3,"dRow":1,"dCol":0},{"word":"FOG","row":9,"col":2,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-seasons',
    topic: "Seasons",
    topicSlug: 'seasons',
    difficulty: 'hard',
    size: 10,
    grid: ["WTEOTSORFM","BLOSSOMETW","OESBUDSMRI","NALSNOWMAN","FVEFSUAUUT","IEDFHUSSTE","RSGNIRPSUR","EIEANSANMB","HARVESTVNL","WCINCIPUES"],
    words: [{"word":"SUNSHINE","row":1,"col":4,"dRow":1,"dCol":0},{"word":"BLOSSOM","row":1,"col":0,"dRow":0,"dCol":1},{"word":"HARVEST","row":8,"col":0,"dRow":0,"dCol":1},{"word":"SNOWMAN","row":3,"col":3,"dRow":0,"dCol":1},{"word":"BONFIRE","row":1,"col":0,"dRow":1,"dCol":0},{"word":"SPRING","row":6,"col":7,"dRow":0,"dCol":-1},{"word":"SUMMER","row":5,"col":7,"dRow":-1,"dCol":0},{"word":"AUTUMN","row":3,"col":8,"dRow":1,"dCol":0},{"word":"WINTER","row":1,"col":9,"dRow":1,"dCol":0},{"word":"LEAVES","row":1,"col":1,"dRow":1,"dCol":0},{"word":"PICNIC","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"SLEDGE","row":2,"col":2,"dRow":1,"dCol":0},{"word":"FROST","row":0,"col":8,"dRow":0,"dCol":-1},{"word":"BUDS","row":2,"col":3,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-space',
    topic: "Space",
    topicSlug: 'space',
    difficulty: 'hard',
    size: 10,
    grid: ["XTECRATERR","MRTABTEMOC","NRUTASNRRA","YNEBULAEBN","XOARLTLPIN","AOEOSSPNTI","LMEESPILCE","ALTTARTORA","GLVENUSTIL","SRAMROCKET"],
    words: [{"word":"ECLIPSE","row":6,"col":9,"dRow":0,"dCol":-1},{"word":"PLANET","row":5,"col":6,"dRow":-1,"dCol":0},{"word":"GALAXY","row":8,"col":0,"dRow":-1,"dCol":0},{"word":"ROCKET","row":9,"col":4,"dRow":0,"dCol":1},{"word":"CRATER","row":0,"col":3,"dRow":0,"dCol":1},{"word":"METEOR","row":9,"col":3,"dRow":-1,"dCol":0},{"word":"SATURN","row":2,"col":5,"dRow":0,"dCol":-1},{"word":"NEBULA","row":3,"col":1,"dRow":0,"dCol":1},{"word":"COMET","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"ORBIT","row":1,"col":8,"dRow":1,"dCol":0},{"word":"VENUS","row":8,"col":2,"dRow":0,"dCol":1},{"word":"MARS","row":9,"col":3,"dRow":0,"dCol":-1},{"word":"MOON","row":6,"col":1,"dRow":-1,"dCol":0},{"word":"STAR","row":5,"col":4,"dRow":-1,"dCol":1}],
  },
  {
    id: 'local-the-beach',
    topic: "The Beach",
    topicSlug: 'the-beach',
    difficulty: 'hard',
    size: 10,
    grid: ["DDECKCHAIR","FNFELBBEPE","SBKTFRUSSI","ILSSITWPEP","VSHTADPANK","DSEAWEEDVT","ROLBUCKETE","FKLLDNASSA","SDLEWOTASL","LLUGCLIFFI"],
    words: [{"word":"DECKCHAIR","row":0,"col":1,"dRow":0,"dCol":1},{"word":"SEAWEED","row":5,"col":1,"dRow":0,"dCol":1},{"word":"BUCKET","row":6,"col":3,"dRow":0,"dCol":1},{"word":"PEBBLE","row":1,"col":8,"dRow":0,"dCol":-1},{"word":"SHELL","row":3,"col":2,"dRow":1,"dCol":0},{"word":"SPADE","row":2,"col":7,"dRow":1,"dCol":0},{"word":"TOWEL","row":8,"col":6,"dRow":0,"dCol":-1},{"word":"CLIFF","row":9,"col":4,"dRow":0,"dCol":1},{"word":"SAND","row":7,"col":7,"dRow":0,"dCol":-1},{"word":"WAVE","row":3,"col":6,"dRow":1,"dCol":1},{"word":"TIDE","row":2,"col":3,"dRow":1,"dCol":1},{"word":"SURF","row":2,"col":7,"dRow":0,"dCol":-1},{"word":"GULL","row":9,"col":3,"dRow":0,"dCol":-1},{"word":"PIER","row":3,"col":9,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-camping',
    topic: "Camping",
    topicSlug: 'camping',
    difficulty: 'hard',
    size: 10,
    grid: ["AMNOSTOVEP","DKGNIPEELS","AOCWOODSKR","SREOTORCHO","TTMNMPANAP","OPCAMPFIRE","OFOCKTAAAM","BNPCVNLSAA","KLANTERNSO","TBMKETTLEP"],
    words: [{"word":"SLEEPING","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"BACKPACK","row":9,"col":1,"dRow":-1,"dCol":1},{"word":"CAMPFIRE","row":5,"col":2,"dRow":0,"dCol":1},{"word":"COMPASS","row":2,"col":2,"dRow":1,"dCol":1},{"word":"LANTERN","row":8,"col":1,"dRow":0,"dCol":1},{"word":"KETTLE","row":9,"col":3,"dRow":0,"dCol":1},{"word":"TORCH","row":3,"col":4,"dRow":0,"dCol":1},{"word":"BOOTS","row":7,"col":0,"dRow":-1,"dCol":0},{"word":"STOVE","row":0,"col":4,"dRow":0,"dCol":1},{"word":"WOODS","row":2,"col":3,"dRow":0,"dCol":1},{"word":"TENT","row":9,"col":5,"dRow":-1,"dCol":0},{"word":"FIRE","row":5,"col":6,"dRow":0,"dCol":1},{"word":"ROPE","row":2,"col":9,"dRow":1,"dCol":0},{"word":"MAP","row":9,"col":2,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-in-the-garden',
    topic: "In the Garden",
    topicSlug: 'in-the-garden',
    difficulty: 'hard',
    size: 10,
    grid: ["COMPOSTTDP","ALFHDEHCHE","PHSEREWOLF","OUEPOTEEWL","BWNWALGCPE","DOTSWDENEE","SRAKEEEERE","HEWHDERFDS","ESOHHADRSS","DTROWELEOH"],
    words: [{"word":"COMPOST","row":0,"col":0,"dRow":0,"dCol":1},{"word":"FLOWER","row":2,"col":9,"dRow":0,"dCol":-1},{"word":"TROWEL","row":9,"col":1,"dRow":0,"dCol":1},{"word":"SPADE","row":2,"col":2,"dRow":1,"dCol":1},{"word":"HEDGE","row":7,"col":3,"dRow":-1,"dCol":1},{"word":"FENCE","row":7,"col":7,"dRow":-1,"dCol":0},{"word":"SHED","row":6,"col":0,"dRow":1,"dCol":0},{"word":"HOSE","row":8,"col":3,"dRow":0,"dCol":-1},{"word":"WEED","row":4,"col":1,"dRow":-1,"dCol":1},{"word":"LAWN","row":4,"col":5,"dRow":0,"dCol":-1},{"word":"SEED","row":5,"col":3,"dRow":1,"dCol":1},{"word":"BUSH","row":4,"col":0,"dRow":-1,"dCol":1},{"word":"RAKE","row":6,"col":1,"dRow":0,"dCol":1},{"word":"POT","row":3,"col":3,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-trees',
    topic: "Trees",
    topicSlug: 'trees',
    difficulty: 'hard',
    size: 10,
    grid: ["OAKPDHEBWB","BHSYONLYWR","IOOHIPRMLO","RLOPWILLOW","CLRADECAEA","HYAMAPLERN","YCILWHECED","BBEECHZERB","EPLEAZAAAE","PALDERHAEP"],
    words: [{"word":"WILLOW","row":3,"col":4,"dRow":0,"dCol":1},{"word":"POPLAR","row":0,"col":3,"dRow":1,"dCol":1},{"word":"BIRCH","row":1,"col":0,"dRow":1,"dCol":0},{"word":"MAPLE","row":5,"col":3,"dRow":0,"dCol":1},{"word":"CEDAR","row":4,"col":6,"dRow":0,"dCol":-1},{"word":"BEECH","row":7,"col":1,"dRow":0,"dCol":1},{"word":"HOLLY","row":1,"col":1,"dRow":1,"dCol":0},{"word":"ROWAN","row":1,"col":9,"dRow":1,"dCol":0},{"word":"ALDER","row":9,"col":1,"dRow":0,"dCol":1},{"word":"HAZEL","row":9,"col":6,"dRow":-1,"dCol":0},{"word":"PINE","row":3,"col":3,"dRow":-1,"dCol":1},{"word":"OAK","row":0,"col":0,"dRow":0,"dCol":1},{"word":"ELM","row":4,"col":5,"dRow":-1,"dCol":1},{"word":"ASH","row":0,"col":1,"dRow":1,"dCol":1}],
  },
  {
    id: 'local-flowers',
    topic: "Flowers",
    topicSlug: 'flowers',
    difficulty: 'hard',
    size: 10,
    grid: ["AIROTDDPPT","AYSIRIANAL","TNHLHEHINI","ESCCLCLPSL","LHRAPRIUYY","OOZUIOALNP","IADOLCAOOP","VYNYUUYUEO","IAINTSEHPP","ALRESORSLN"],
    words: [{"word":"ORCHID","row":5,"col":1,"dRow":-1,"dCol":1},{"word":"VIOLET","row":7,"col":0,"dRow":-1,"dCol":0},{"word":"DAHLIA","row":0,"col":6,"dRow":1,"dCol":0},{"word":"CROCUS","row":3,"col":5,"dRow":1,"dCol":0},{"word":"AZALEA","row":6,"col":1,"dRow":-1,"dCol":1},{"word":"TULIP","row":8,"col":4,"dRow":-1,"dCol":0},{"word":"DAISY","row":0,"col":5,"dRow":1,"dCol":1},{"word":"POPPY","row":8,"col":9,"dRow":-1,"dCol":0},{"word":"PANSY","row":0,"col":8,"dRow":1,"dCol":0},{"word":"PEONY","row":8,"col":8,"dRow":-1,"dCol":0},{"word":"LUPIN","row":5,"col":7,"dRow":-1,"dCol":0},{"word":"ROSE","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"LILY","row":1,"col":9,"dRow":1,"dCol":0},{"word":"IRIS","row":1,"col":5,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-sports',
    topic: "Sports",
    topicSlug: 'sports',
    difficulty: 'hard',
    size: 10,
    grid: ["TRCHTBCEJC","IKYDOEEIUR","CSCCGCNCDY","ARLENAKNOG","EGITIRNEII","GNNCICITYS","EIGFKHIBBC","TXLASEKAGI","SOCCERTLUL","GBKLBYOLRY"],
    words: [{"word":"CRICKET","row":2,"col":0,"dRow":1,"dCol":1},{"word":"CYCLING","row":0,"col":2,"dRow":1,"dCol":0},{"word":"NETBALL","row":3,"col":7,"dRow":1,"dCol":0},{"word":"ARCHERY","row":3,"col":5,"dRow":1,"dCol":0},{"word":"SOCCER","row":8,"col":0,"dRow":0,"dCol":1},{"word":"TENNIS","row":0,"col":4,"dRow":1,"dCol":1},{"word":"HOCKEY","row":0,"col":3,"dRow":1,"dCol":1},{"word":"BOXING","row":9,"col":1,"dRow":-1,"dCol":0},{"word":"SKIING","row":7,"col":4,"dRow":-1,"dCol":0},{"word":"RUGBY","row":9,"col":8,"dRow":-1,"dCol":0},{"word":"GOLF","row":9,"col":0,"dRow":-1,"dCol":1},{"word":"JUDO","row":0,"col":8,"dRow":1,"dCol":0}],
  },
  {
    id: 'local-olympic-events',
    topic: "Olympic Events",
    topicSlug: 'olympic-events',
    difficulty: 'hard',
    size: 10,
    grid: ["LIBOXINGAA","HURDLESNWN","ESSJMEMIIS","OAUPANXWFH","YICTRVLOEO","ALSLAIERNO","LIIUTONLCT","ENDAHIITII","RGEVODUJNN","DIVINGSIGG"],
    words: [{"word":"SHOOTING","row":2,"col":9,"dRow":1,"dCol":0},{"word":"MARATHON","row":2,"col":4,"dRow":1,"dCol":0},{"word":"HURDLES","row":1,"col":0,"dRow":0,"dCol":1},{"word":"JAVELIN","row":2,"col":3,"dRow":1,"dCol":1},{"word":"FENCING","row":3,"col":8,"dRow":1,"dCol":0},{"word":"SAILING","row":2,"col":1,"dRow":1,"dCol":0},{"word":"SPRINT","row":2,"col":2,"dRow":1,"dCol":1},{"word":"DISCUS","row":7,"col":2,"dRow":-1,"dCol":0},{"word":"ROWING","row":5,"col":7,"dRow":-1,"dCol":0},{"word":"DIVING","row":9,"col":0,"dRow":0,"dCol":1},{"word":"BOXING","row":0,"col":2,"dRow":0,"dCol":1},{"word":"RELAY","row":8,"col":0,"dRow":-1,"dCol":0},{"word":"VAULT","row":8,"col":3,"dRow":-1,"dCol":0},{"word":"JUDO","row":8,"col":7,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-musical-instruments',
    topic: "Musical Instruments",
    topicSlug: 'musical-instruments',
    difficulty: 'hard',
    size: 10,
    grid: ["IARHTCLNTN","UTVGAVELEA","TDRUMIILFG","BUMIEOBOLR","AUBTELUIUO","NCLARINETA","JPTRENRBEL","ORTRUMPETO","OAIAPIANOI","EHCDULAFNV"],
    words: [{"word":"CLARINET","row":5,"col":1,"dRow":0,"dCol":1},{"word":"TRUMPET","row":7,"col":2,"dRow":0,"dCol":1},{"word":"GUITAR","row":1,"col":3,"dRow":1,"dCol":0},{"word":"VIOLIN","row":1,"col":5,"dRow":1,"dCol":0},{"word":"PIANO","row":8,"col":4,"dRow":0,"dCol":1},{"word":"FLUTE","row":2,"col":8,"dRow":1,"dCol":0},{"word":"CELLO","row":0,"col":5,"dRow":1,"dCol":1},{"word":"BANJO","row":3,"col":0,"dRow":1,"dCol":0},{"word":"VIOLA","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"ORGAN","row":4,"col":9,"dRow":-1,"dCol":0},{"word":"DRUM","row":2,"col":1,"dRow":0,"dCol":1},{"word":"HARP","row":9,"col":1,"dRow":-1,"dCol":0},{"word":"OBOE","row":3,"col":7,"dRow":0,"dCol":-1},{"word":"TUBA","row":2,"col":0,"dRow":1,"dCol":1}],
  },
  {
    id: 'local-music-words',
    topic: "Music Words",
    topicSlug: 'music-words',
    difficulty: 'hard',
    size: 10,
    grid: ["TAEBDCYTTU","AHSSRDNABB","SBTCONCERT","IOELHIMMDA","NPEHCGHUPS","GMLENUTBLO","EEAEALYLIU","RTCIBRHABT","BTSHSUROHC","LYRICSTAGE"],
    words: [{"word":"CONCERT","row":2,"col":3,"dRow":0,"dCol":1},{"word":"MELODY","row":5,"col":1,"dRow":-1,"dCol":1},{"word":"RHYTHM","row":8,"col":6,"dRow":-1,"dCol":0},{"word":"CHORUS","row":8,"col":9,"dRow":0,"dCol":-1},{"word":"LYRICS","row":9,"col":0,"dRow":0,"dCol":1},{"word":"SINGER","row":2,"col":0,"dRow":1,"dCol":0},{"word":"TEMPO","row":7,"col":1,"dRow":-1,"dCol":0},{"word":"CHORD","row":4,"col":4,"dRow":-1,"dCol":0},{"word":"SCALE","row":8,"col":2,"dRow":-1,"dCol":0},{"word":"ALBUM","row":7,"col":7,"dRow":-1,"dCol":0},{"word":"STAGE","row":9,"col":5,"dRow":0,"dCol":1},{"word":"BEAT","row":0,"col":3,"dRow":0,"dCol":-1},{"word":"TUNE","row":5,"col":6,"dRow":0,"dCol":-1},{"word":"BAND","row":1,"col":8,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-colours',
    topic: "Colours",
    topicSlug: 'colours',
    difficulty: 'hard',
    size: 10,
    grid: ["UCGELPRUPD","TBYVSPKAPE","EGAIECNTRR","LRGOAEEULB","REVLISPERR","AEBEEGNARO","CNNTDLOGUW","SLIEPINKON","RHELYELLOW","WEAPRLREGD"],
    words: [{"word":"SCARLET","row":7,"col":0,"dRow":-1,"dCol":0},{"word":"YELLOW","row":8,"col":4,"dRow":0,"dCol":1},{"word":"PURPLE","row":0,"col":8,"dRow":0,"dCol":-1},{"word":"ORANGE","row":5,"col":9,"dRow":0,"dCol":-1},{"word":"SILVER","row":4,"col":5,"dRow":0,"dCol":-1},{"word":"VIOLET","row":1,"col":3,"dRow":1,"dCol":0},{"word":"GREEN","row":2,"col":1,"dRow":1,"dCol":0},{"word":"BROWN","row":3,"col":9,"dRow":1,"dCol":0},{"word":"BLACK","row":5,"col":2,"dRow":-1,"dCol":1},{"word":"WHITE","row":9,"col":0,"dRow":-1,"dCol":1},{"word":"BLUE","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"PINK","row":7,"col":4,"dRow":0,"dCol":1},{"word":"GOLD","row":6,"col":7,"dRow":0,"dCol":-1},{"word":"RED","row":2,"col":9,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-shapes',
    topic: "Shapes",
    topicSlug: 'shapes',
    difficulty: 'hard',
    size: 10,
    grid: ["HDDSGLROOM","EBICRATRQD","XESATVCMQE","AGUSMOEOCR","GDBCQOREIE","OEMUOUNDRH","NWOBBNADCP","SAHESQERLS","RTRIANGLET","GSPOMSIRPB"],
    words: [{"word":"TRIANGLE","row":8,"col":1,"dRow":0,"dCol":1},{"word":"DIAMOND","row":0,"col":1,"dRow":1,"dCol":1},{"word":"HEXAGON","row":0,"col":0,"dRow":1,"dCol":0},{"word":"RHOMBUS","row":8,"col":2,"dRow":-1,"dCol":0},{"word":"CIRCLE","row":3,"col":8,"dRow":1,"dCol":0},{"word":"SQUARE","row":3,"col":3,"dRow":1,"dCol":1},{"word":"SPHERE","row":7,"col":9,"dRow":-1,"dCol":0},{"word":"PRISM","row":9,"col":8,"dRow":0,"dCol":-1},{"word":"WEDGE","row":6,"col":1,"dRow":-1,"dCol":0},{"word":"OVAL","row":3,"col":5,"dRow":-1,"dCol":0},{"word":"STAR","row":3,"col":3,"dRow":-1,"dCol":1},{"word":"CUBE","row":4,"col":3,"dRow":1,"dCol":0},{"word":"CONE","row":4,"col":3,"dRow":1,"dCol":1},{"word":"ARC","row":1,"col":5,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-school',
    topic: "School",
    topicSlug: 'school',
    difficulty: 'hard',
    size: 10,
    grid: ["WKSSALCTCR","LKRPKHDESK","EEAELOOAHM","SLANAMTCME","SATCHELHAT","OECICWOEXR","NBELCOSREO","HEYRARBILP","SLBOOKLRCE","SLESBRELUR"],
    words: [{"word":"HOMEWORK","row":1,"col":5,"dRow":1,"dCol":0},{"word":"TEACHER","row":0,"col":7,"dRow":1,"dCol":0},{"word":"LIBRARY","row":7,"col":8,"dRow":0,"dCol":-1},{"word":"SATCHEL","row":4,"col":0,"dRow":0,"dCol":1},{"word":"PENCIL","row":1,"col":3,"dRow":1,"dCol":0},{"word":"LESSON","row":1,"col":0,"dRow":1,"dCol":0},{"word":"REPORT","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"RULER","row":9,"col":9,"dRow":0,"dCol":-1},{"word":"CLASS","row":0,"col":6,"dRow":0,"dCol":-1},{"word":"CHALK","row":5,"col":4,"dRow":-1,"dCol":0},{"word":"BOOK","row":8,"col":2,"dRow":0,"dCol":1},{"word":"DESK","row":1,"col":6,"dRow":0,"dCol":1},{"word":"BELL","row":6,"col":1,"dRow":1,"dCol":0},{"word":"EXAM","row":6,"col":8,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-maths',
    topic: "Maths",
    topicSlug: 'maths',
    difficulty: 'hard',
    size: 10,
    grid: ["PMFNDNMIAC","EURUOITARG","GSAMTIMESI","RSCBAESLEA","AMTENSAEEN","PIIRIUARAG","HNONQCAASL","DUNEDIVIDE","CSDECIMALD","ANEMIRPOSD"],
    words: [{"word":"FRACTION","row":0,"col":2,"dRow":1,"dCol":0},{"word":"DECIMAL","row":8,"col":2,"dRow":0,"dCol":1},{"word":"NUMBER","row":0,"col":3,"dRow":1,"dCol":0},{"word":"DIVIDE","row":7,"col":4,"dRow":0,"dCol":1},{"word":"EQUALS","row":7,"col":3,"dRow":-1,"dCol":1},{"word":"MINUS","row":4,"col":1,"dRow":1,"dCol":0},{"word":"TIMES","row":2,"col":4,"dRow":0,"dCol":1},{"word":"ANGLE","row":3,"col":9,"dRow":1,"dCol":0},{"word":"GRAPH","row":2,"col":0,"dRow":1,"dCol":0},{"word":"PRIME","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"RATIO","row":1,"col":8,"dRow":0,"dCol":-1},{"word":"AREA","row":6,"col":6,"dRow":-1,"dCol":1},{"word":"ADD","row":6,"col":7,"dRow":1,"dCol":1},{"word":"SUM","row":2,"col":1,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-science',
    topic: "Science",
    topicSlug: 'science',
    difficulty: 'hard',
    size: 10,
    grid: ["LIQUIDGEEI","YCSTTTHGIL","EOFEEIATOM","BDOCNUMMYI","OISRECGAST","RLSORRGGDY","COIFGIINME","ISLIYCCELL","MDGRAVITYI","OCDNUOSDNE"],
    words: [{"word":"GRAVITY","row":8,"col":2,"dRow":0,"dCol":1},{"word":"CIRCUIT","row":7,"col":5,"dRow":-1,"dCol":0},{"word":"MICROBE","row":8,"col":0,"dRow":-1,"dCol":0},{"word":"ENERGY","row":2,"col":4,"dRow":1,"dCol":0},{"word":"MAGNET","row":3,"col":7,"dRow":1,"dCol":0},{"word":"LIQUID","row":0,"col":0,"dRow":0,"dCol":1},{"word":"FOSSIL","row":2,"col":2,"dRow":1,"dCol":0},{"word":"SOLID","row":7,"col":1,"dRow":-1,"dCol":0},{"word":"FORCE","row":6,"col":3,"dRow":-1,"dCol":0},{"word":"LIGHT","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"SOUND","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"ATOM","row":2,"col":6,"dRow":0,"dCol":1},{"word":"CELL","row":7,"col":6,"dRow":0,"dCol":1},{"word":"GAS","row":4,"col":6,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-the-human-body',
    topic: "The Human Body",
    topicSlug: 'the-human-body',
    difficulty: 'hard',
    size: 10,
    grid: ["WNHBLELSEB","RLKBOELKNA","INIRELUSNE","SNDAPCKINR","TRNIESSONH","LEENGUBSEE","KVYNSMYPRA","MIUSUNSIVR","ELUHLEMNET","VRTWOBLEEN"],
    words: [{"word":"MUSCLE","row":6,"col":5,"dRow":-1,"dCol":0},{"word":"KIDNEY","row":1,"col":2,"dRow":1,"dCol":0},{"word":"HEART","row":4,"col":9,"dRow":1,"dCol":0},{"word":"BRAIN","row":1,"col":3,"dRow":1,"dCol":0},{"word":"ELBOW","row":9,"col":7,"dRow":0,"dCol":-1},{"word":"ANKLE","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"SPINE","row":5,"col":7,"dRow":1,"dCol":0},{"word":"LIVER","row":8,"col":1,"dRow":-1,"dCol":0},{"word":"THUMB","row":9,"col":2,"dRow":-1,"dCol":1},{"word":"WRIST","row":0,"col":0,"dRow":1,"dCol":0},{"word":"SKULL","row":4,"col":6,"dRow":-1,"dCol":0},{"word":"NERVE","row":4,"col":8,"dRow":1,"dCol":0},{"word":"LUNG","row":8,"col":1,"dRow":-1,"dCol":1},{"word":"BONE","row":5,"col":6,"dRow":-1,"dCol":1}],
  },
  {
    id: 'local-jobs',
    topic: "Jobs",
    topicSlug: 'jobs',
    difficulty: 'hard',
    size: 10,
    grid: ["RUWRITERSF","ROEISBEREB","EYEIVEIHRR","YFTREHCAET","WROTCODDMS","AREBMULPRI","LVTOLIPAAT","SESRUNHEFN","ATEBAKEREE","MPTESRIRTD"],
    words: [{"word":"TEACHER","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"PLUMBER","row":5,"col":7,"dRow":0,"dCol":-1},{"word":"DENTIST","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"BUILDER","row":8,"col":3,"dRow":-1,"dCol":1},{"word":"DOCTOR","row":4,"col":6,"dRow":0,"dCol":-1},{"word":"FARMER","row":7,"col":8,"dRow":-1,"dCol":0},{"word":"ARTIST","row":5,"col":0,"dRow":-1,"dCol":1},{"word":"LAWYER","row":6,"col":0,"dRow":-1,"dCol":0},{"word":"WRITER","row":0,"col":2,"dRow":0,"dCol":1},{"word":"BAKER","row":8,"col":3,"dRow":0,"dCol":1},{"word":"PILOT","row":6,"col":6,"dRow":0,"dCol":-1},{"word":"NURSE","row":7,"col":5,"dRow":0,"dCol":-1},{"word":"CHEF","row":3,"col":6,"dRow":-1,"dCol":1},{"word":"VET","row":6,"col":1,"dRow":1,"dCol":0}],
  },
  {
    id: 'local-transport',
    topic: "Transport",
    topicSlug: 'transport',
    difficulty: 'hard',
    size: 10,
    grid: ["TTKURYRANC","ENIARTEVAN","KBARILLRAE","COESCOOTER","OFVYTRVAAO","RACEERLXLT","SIANSYAITC","BBNAUATMCA","AOOLBOATOR","OCEPIMERTT"],
    words: [{"word":"BICYCLE","row":7,"col":0,"dRow":-1,"dCol":1},{"word":"SCOOTER","row":3,"col":3,"dRow":0,"dCol":1},{"word":"TRACTOR","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"ROCKET","row":5,"col":0,"dRow":-1,"dCol":0},{"word":"TRAIN","row":1,"col":5,"dRow":0,"dCol":-1},{"word":"PLANE","row":9,"col":3,"dRow":-1,"dCol":0},{"word":"FERRY","row":4,"col":1,"dRow":-1,"dCol":1},{"word":"LORRY","row":2,"col":5,"dRow":1,"dCol":0},{"word":"CANOE","row":5,"col":2,"dRow":1,"dCol":0},{"word":"TRAM","row":4,"col":4,"dRow":1,"dCol":1},{"word":"TAXI","row":3,"col":7,"dRow":1,"dCol":0},{"word":"BOAT","row":8,"col":4,"dRow":0,"dCol":1},{"word":"BUS","row":8,"col":4,"dRow":-1,"dCol":0},{"word":"VAN","row":1,"col":7,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-countries',
    topic: "Countries",
    topicSlug: 'countries',
    difficulty: 'hard',
    size: 10,
    grid: ["CMGYAYNEKA","HEAENAACIA","IXANAEPNEA","LIBODGAACI","ECRRAYJRED","GOAWNPEFEN","HGZAATYARI","JOIYCYFYGA","POLANDUREP","LIRLBBINIS"],
    words: [{"word":"FRANCE","row":5,"col":7,"dRow":-1,"dCol":0},{"word":"BRAZIL","row":3,"col":2,"dRow":1,"dCol":0},{"word":"CANADA","row":7,"col":4,"dRow":-1,"dCol":0},{"word":"NORWAY","row":2,"col":3,"dRow":1,"dCol":0},{"word":"MEXICO","row":0,"col":1,"dRow":1,"dCol":0},{"word":"GREECE","row":7,"col":8,"dRow":-1,"dCol":0},{"word":"POLAND","row":8,"col":0,"dRow":0,"dCol":1},{"word":"SPAIN","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"JAPAN","row":4,"col":6,"dRow":-1,"dCol":0},{"word":"EGYPT","row":2,"col":5,"dRow":1,"dCol":0},{"word":"KENYA","row":0,"col":8,"dRow":0,"dCol":-1},{"word":"CHILE","row":0,"col":0,"dRow":1,"dCol":0},{"word":"INDIA","row":6,"col":9,"dRow":-1,"dCol":0},{"word":"PERU","row":8,"col":9,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-capital-cities',
    topic: "Capital Cities",
    topicSlug: 'capital-cities',
    difficulty: 'hard',
    size: 10,
    grid: ["DSOBEMORLA","HNOTTAWAPO","TTLONDONRO","RLSNORIACT","ESESLISBON","TIUNHDGOIP","VRGEBERLIN","IAAHLKBSBA","IPRTLUAOOB","GDPADOYKOT"],
    words: [{"word":"MADRID","row":0,"col":5,"dRow":1,"dCol":0},{"word":"LONDON","row":2,"col":2,"dRow":0,"dCol":1},{"word":"LISBON","row":4,"col":4,"dRow":0,"dCol":1},{"word":"VIENNA","row":6,"col":0,"dRow":-1,"dCol":1},{"word":"ATHENS","row":9,"col":3,"dRow":-1,"dCol":0},{"word":"DUBLIN","row":9,"col":4,"dRow":-1,"dCol":1},{"word":"OTTAWA","row":1,"col":2,"dRow":0,"dCol":1},{"word":"BERLIN","row":6,"col":4,"dRow":0,"dCol":1},{"word":"PRAGUE","row":9,"col":2,"dRow":-1,"dCol":0},{"word":"PARIS","row":8,"col":1,"dRow":-1,"dCol":0},{"word":"CAIRO","row":3,"col":8,"dRow":0,"dCol":-1},{"word":"TOKYO","row":9,"col":9,"dRow":0,"dCol":-1},{"word":"ROME","row":0,"col":7,"dRow":0,"dCol":-1},{"word":"OSLO","row":8,"col":7,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-rivers-and-lakes',
    topic: "Rivers and Lakes",
    topicSlug: 'rivers-and-lakes',
    difficulty: 'hard',
    size: 10,
    grid: ["EDTESTIIBR","OPONDTTRRS","NETSNNRWTS","AATBEREEDW","CBERADPIAR","UARIONPRTM","LUSDAAKULP","CGRGRBOHEA","RIVERRKTDS","RARUTMARSH"],
    words: [{"word":"CURRENT","row":7,"col":0,"dRow":-1,"dCol":1},{"word":"STREAM","row":0,"col":4,"dRow":1,"dCol":1},{"word":"RAPIDS","row":7,"col":4,"dRow":-1,"dCol":1},{"word":"BRIDGE","row":3,"col":3,"dRow":1,"dCol":0},{"word":"RIVER","row":8,"col":0,"dRow":0,"dCol":1},{"word":"DELTA","row":8,"col":8,"dRow":-1,"dCol":0},{"word":"OTTER","row":1,"col":2,"dRow":1,"dCol":0},{"word":"TROUT","row":9,"col":4,"dRow":-1,"dCol":1},{"word":"CANOE","row":4,"col":0,"dRow":-1,"dCol":0},{"word":"MARSH","row":9,"col":5,"dRow":0,"dCol":1},{"word":"BANK","row":3,"col":3,"dRow":1,"dCol":1},{"word":"REED","row":3,"col":5,"dRow":0,"dCol":1},{"word":"WEIR","row":2,"col":7,"dRow":1,"dCol":0},{"word":"POND","row":1,"col":1,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-mountains',
    topic: "Mountains",
    topicSlug: 'mountains',
    difficulty: 'hard',
    size: 10,
    grid: ["AGRRIRILET","SRLEGSNOWI","CIWAVALLEY","ERRNCCCOEL","NCSCLIFFPI","TBOULDERNE","RNEPMIRRGE","AROPEMIDEN","ILRTRAIEOS","LPIECRKTPP"],
    words: [{"word":"GLACIER","row":0,"col":1,"dRow":1,"dCol":1},{"word":"BOULDER","row":5,"col":1,"dRow":0,"dCol":1},{"word":"SUMMIT","row":4,"col":2,"dRow":1,"dCol":1},{"word":"VALLEY","row":2,"col":4,"dRow":0,"dCol":1},{"word":"ASCENT","row":0,"col":0,"dRow":1,"dCol":0},{"word":"RIDGE","row":9,"col":5,"dRow":-1,"dCol":1},{"word":"SLOPE","row":1,"col":5,"dRow":1,"dCol":1},{"word":"CLIFF","row":4,"col":3,"dRow":0,"dCol":1},{"word":"TRAIL","row":5,"col":0,"dRow":1,"dCol":0},{"word":"CAIRN","row":9,"col":4,"dRow":-1,"dCol":1},{"word":"PEAK","row":6,"col":3,"dRow":1,"dCol":1},{"word":"CRAG","row":4,"col":1,"dRow":-1,"dCol":1},{"word":"SNOW","row":1,"col":5,"dRow":0,"dCol":1},{"word":"ROPE","row":7,"col":1,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-dinosaurs',
    topic: "Dinosaurs",
    topicSlug: 'dinosaurs',
    difficulty: 'hard',
    size: 10,
    grid: ["BONESPIKEI","OACISSARUJ","RSKULLJCTS","OEROVIBREH","TXIWGPWALC","PTLSLISSOF","AIXREBMASE","RNSCALESSR","LCIXTSRGLN","MTUITAILGE"],
    words: [{"word":"HERBIVORE","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"JURASSIC","row":1,"col":9,"dRow":0,"dCol":-1},{"word":"EXTINCT","row":3,"col":1,"dRow":1,"dCol":0},{"word":"FOSSIL","row":5,"col":9,"dRow":0,"dCol":-1},{"word":"RAPTOR","row":7,"col":0,"dRow":-1,"dCol":0},{"word":"SCALES","row":7,"col":2,"dRow":0,"dCol":1},{"word":"SPIKE","row":0,"col":4,"dRow":0,"dCol":1},{"word":"BONES","row":0,"col":0,"dRow":0,"dCol":1},{"word":"SKULL","row":2,"col":1,"dRow":0,"dCol":1},{"word":"AMBER","row":6,"col":7,"dRow":0,"dCol":-1},{"word":"CLAW","row":4,"col":9,"dRow":0,"dCol":-1},{"word":"TAIL","row":9,"col":4,"dRow":0,"dCol":1},{"word":"FERN","row":5,"col":9,"dRow":1,"dCol":0},{"word":"EGG","row":7,"col":6,"dRow":1,"dCol":1}],
  },
  {
    id: 'local-castles-and-knights',
    topic: "Castles and Knights",
    topicSlug: 'castles-and-knights',
    difficulty: 'hard',
    size: 10,
    grid: ["CHEAKNIGHT","MRTMOORRES","SUOREEOLTU","HOWWHWTARO","IMECNSHURJ","ERRTATRNCI","LAACSWORDC","DNRRENNABH","RUDLAREHET","EETAGKTAOM"],
    words: [{"word":"CASTLE","row":6,"col":3,"dRow":-1,"dCol":1},{"word":"KNIGHT","row":0,"col":4,"dRow":0,"dCol":1},{"word":"SHIELD","row":2,"col":0,"dRow":1,"dCol":0},{"word":"ARMOUR","row":6,"col":1,"dRow":-1,"dCol":0},{"word":"BANNER","row":7,"col":8,"dRow":0,"dCol":-1},{"word":"THRONE","row":3,"col":6,"dRow":1,"dCol":0},{"word":"ARCHER","row":6,"col":1,"dRow":-1,"dCol":1},{"word":"HERALD","row":8,"col":7,"dRow":0,"dCol":-1},{"word":"SWORD","row":6,"col":4,"dRow":0,"dCol":1},{"word":"TOWER","row":1,"col":2,"dRow":1,"dCol":0},{"word":"JOUST","row":4,"col":9,"dRow":-1,"dCol":0},{"word":"CROWN","row":0,"col":0,"dRow":1,"dCol":1},{"word":"MOAT","row":9,"col":9,"dRow":0,"dCol":-1},{"word":"GATE","row":9,"col":4,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-pirates',
    topic: "Pirates",
    topicSlug: 'pirates',
    difficulty: 'hard',
    size: 10,
    grid: ["OWOEAGOLDA","SERRKMSAIL","PRAUNCDGLD","ACSSAPMOCO","REHALGCOSS","RLEEPRPNSR","OHERSHIPSC","TEMTOTOPNR","TSAMISLAND","MNPROHCNAT"],
    words: [{"word":"TREASURE","row":7,"col":3,"dRow":-1,"dCol":0},{"word":"COMPASS","row":3,"col":8,"dRow":0,"dCol":-1},{"word":"PARROT","row":2,"col":0,"dRow":1,"dCol":0},{"word":"ANCHOR","row":9,"col":8,"dRow":0,"dCol":-1},{"word":"ISLAND","row":8,"col":4,"dRow":0,"dCol":1},{"word":"LAGOON","row":0,"col":7,"dRow":1,"dCol":0},{"word":"CHEST","row":3,"col":1,"dRow":1,"dCol":1},{"word":"PLANK","row":5,"col":4,"dRow":-1,"dCol":0},{"word":"SHIP","row":6,"col":4,"dRow":0,"dCol":1},{"word":"SAIL","row":1,"col":6,"dRow":0,"dCol":1},{"word":"GOLD","row":0,"col":5,"dRow":0,"dCol":1},{"word":"CREW","row":3,"col":1,"dRow":-1,"dCol":0},{"word":"MAST","row":8,"col":3,"dRow":0,"dCol":-1},{"word":"MAP","row":7,"col":2,"dRow":1,"dCol":0}],
  },
  {
    id: 'local-fairy-tales',
    topic: "Fairy Tales",
    topicSlug: 'fairy-tales',
    difficulty: 'hard',
    size: 10,
    grid: ["MIRRORHEPA","TNAIGFENPW","SRACCDLOPE","ERSWTTTGCW","REPPILSARS","OCCSETARON","FNIGWLCDWA","NIGPRNLHNE","HRAHSIWNGB","LPMREWOTRP"],
    words: [{"word":"SLIPPER","row":4,"col":6,"dRow":0,"dCol":-1},{"word":"PRINCE","row":9,"col":1,"dRow":-1,"dCol":0},{"word":"CASTLE","row":6,"col":6,"dRow":-1,"dCol":0},{"word":"DRAGON","row":6,"col":7,"dRow":-1,"dCol":0},{"word":"FOREST","row":6,"col":0,"dRow":-1,"dCol":0},{"word":"MIRROR","row":0,"col":0,"dRow":0,"dCol":1},{"word":"WITCH","row":3,"col":3,"dRow":1,"dCol":1},{"word":"MAGIC","row":9,"col":2,"dRow":-1,"dCol":0},{"word":"CROWN","row":3,"col":8,"dRow":1,"dCol":0},{"word":"GIANT","row":1,"col":4,"dRow":0,"dCol":-1},{"word":"BEANS","row":8,"col":9,"dRow":-1,"dCol":0},{"word":"SPELL","row":3,"col":2,"dRow":1,"dCol":1},{"word":"TOWER","row":9,"col":7,"dRow":0,"dCol":-1},{"word":"WISH","row":8,"col":6,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-birthdays',
    topic: "Birthdays",
    topicSlug: 'birthdays',
    difficulty: 'hard',
    size: 10,
    grid: ["PMNIBANNER","RIBBONPACB","EWILNPSSNA","SHCFGAMESL","ESIRPRUSPL","NINIITWESO","TWGECYMTIO","ELDNACAKEN","PSADRHTORR","IIRSDSNNEA"],
    words: [{"word":"SURPRISE","row":4,"col":7,"dRow":0,"dCol":-1},{"word":"BALLOON","row":1,"col":9,"dRow":1,"dCol":0},{"word":"PRESENT","row":0,"col":0,"dRow":1,"dCol":0},{"word":"FRIENDS","row":3,"col":3,"dRow":1,"dCol":0},{"word":"CANDLE","row":7,"col":5,"dRow":0,"dCol":-1},{"word":"RIBBON","row":1,"col":0,"dRow":0,"dCol":1},{"word":"BANNER","row":0,"col":4,"dRow":0,"dCol":1},{"word":"PARTY","row":2,"col":5,"dRow":1,"dCol":0},{"word":"GAMES","row":3,"col":4,"dRow":0,"dCol":1},{"word":"ICING","row":2,"col":2,"dRow":1,"dCol":0},{"word":"CAKE","row":7,"col":5,"dRow":0,"dCol":1},{"word":"CARD","row":6,"col":4,"dRow":1,"dCol":0},{"word":"WISH","row":6,"col":1,"dRow":-1,"dCol":0},{"word":"HATS","row":8,"col":5,"dRow":-1,"dCol":1}],
  },
  {
    id: 'local-christmas',
    topic: "Christmas",
    topicSlug: 'christmas',
    difficulty: 'hard',
    size: 10,
    grid: ["PEERTNIBOR","DUREKCARCT","SNDENRTRNB","NLADLESNIT","ONENIHOLLY","WNIIONOTTO","IESEGRGFLS","STARAHRIOL","STOCKINGSE","TRAILEGNAG"],
    words: [{"word":"REINDEER","row":7,"col":3,"dRow":-1,"dCol":0},{"word":"STOCKING","row":8,"col":0,"dRow":0,"dCol":1},{"word":"PUDDING","row":0,"col":0,"dRow":1,"dCol":1},{"word":"CRACKER","row":1,"col":8,"dRow":0,"dCol":-1},{"word":"TINSEL","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"SLEIGH","row":2,"col":0,"dRow":1,"dCol":1},{"word":"CAROL","row":8,"col":3,"dRow":-1,"dCol":1},{"word":"HOLLY","row":4,"col":5,"dRow":0,"dCol":1},{"word":"ANGEL","row":9,"col":8,"dRow":0,"dCol":-1},{"word":"ROBIN","row":0,"col":9,"dRow":0,"dCol":-1},{"word":"TREE","row":0,"col":4,"dRow":0,"dCol":-1},{"word":"STAR","row":7,"col":0,"dRow":0,"dCol":1},{"word":"SNOW","row":2,"col":0,"dRow":1,"dCol":0},{"word":"GIFT","row":8,"col":7,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-halloween',
    topic: "Halloween",
    topicSlug: 'halloween',
    difficulty: 'hard',
    size: 10,
    grid: ["ENIKPMUPOU","OPOSPIDERI","LCOSTUMETS","STEEWSKOLS","OSTAERTWOS","ESOSPOOKYN","NKNORDLUAC","SSLANTERNE","CANDLEPACO","SMOORBAIRO"],
    words: [{"word":"CAULDRON","row":6,"col":9,"dRow":0,"dCol":-1},{"word":"PUMPKIN","row":0,"col":7,"dRow":0,"dCol":-1},{"word":"COSTUME","row":2,"col":1,"dRow":0,"dCol":1},{"word":"LANTERN","row":7,"col":2,"dRow":0,"dCol":1},{"word":"SWEETS","row":3,"col":5,"dRow":0,"dCol":-1},{"word":"SPIDER","row":1,"col":3,"dRow":0,"dCol":1},{"word":"TREATS","row":4,"col":6,"dRow":0,"dCol":-1},{"word":"CANDLE","row":8,"col":0,"dRow":0,"dCol":1},{"word":"SPOOKY","row":5,"col":3,"dRow":0,"dCol":1},{"word":"BROOM","row":9,"col":5,"dRow":0,"dCol":-1},{"word":"MASK","row":9,"col":1,"dRow":-1,"dCol":0},{"word":"MOON","row":2,"col":6,"dRow":1,"dCol":1},{"word":"CAPE","row":8,"col":8,"dRow":0,"dCol":-1},{"word":"OWL","row":5,"col":6,"dRow":-1,"dCol":1}],
  },
  {
    id: 'local-at-the-zoo',
    topic: "At the Zoo",
    topicSlug: 'at-the-zoo',
    difficulty: 'hard',
    size: 10,
    grid: ["KLADNAPRRL","MEDZOTARPE","KMEYIAEHGM","TARPLPDINU","DCRTEIBNIR","OAVIARYODL","TZEBRAROEH","TAKREEMLEF","EUIGIRAFFE","RENCLOSURE"],
    words: [{"word":"ENCLOSURE","row":9,"col":1,"dRow":0,"dCol":1},{"word":"GIRAFFE","row":8,"col":3,"dRow":0,"dCol":1},{"word":"MEERKAT","row":7,"col":6,"dRow":0,"dCol":-1},{"word":"FEEDING","row":8,"col":8,"dRow":-1,"dCol":0},{"word":"KEEPER","row":0,"col":0,"dRow":1,"dCol":1},{"word":"AVIARY","row":5,"col":1,"dRow":0,"dCol":1},{"word":"ZEBRA","row":6,"col":1,"dRow":0,"dCol":1},{"word":"PANDA","row":0,"col":6,"dRow":0,"dCol":-1},{"word":"CAMEL","row":4,"col":1,"dRow":-1,"dCol":0},{"word":"RHINO","row":1,"col":7,"dRow":1,"dCol":0},{"word":"OTTER","row":5,"col":0,"dRow":1,"dCol":0},{"word":"TAPIR","row":1,"col":5,"dRow":1,"dCol":0},{"word":"LEMUR","row":0,"col":9,"dRow":1,"dCol":0},{"word":"LION","row":3,"col":4,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-pets',
    topic: "Pets",
    topicSlug: 'pets',
    difficulty: 'hard',
    size: 10,
    grid: ["EABUDGIECI","URETSMAHCT","BORRALLOCO","DLIBREGHCR","OTIBBARVET","GOLDFISHEO","RRNETTIKTI","YPPUPTSYES","PSTLEADSRE","DCOEBCINKI"],
    words: [{"word":"GOLDFISH","row":5,"col":0,"dRow":0,"dCol":1},{"word":"TORTOISE","row":1,"col":9,"dRow":1,"dCol":0},{"word":"HAMSTER","row":1,"col":7,"dRow":0,"dCol":-1},{"word":"RABBIT","row":4,"col":6,"dRow":0,"dCol":-1},{"word":"GERBIL","row":3,"col":6,"dRow":0,"dCol":-1},{"word":"BUDGIE","row":0,"col":2,"dRow":0,"dCol":1},{"word":"KITTEN","row":6,"col":7,"dRow":0,"dCol":-1},{"word":"BASKET","row":9,"col":4,"dRow":-1,"dCol":1},{"word":"COLLAR","row":2,"col":8,"dRow":0,"dCol":-1},{"word":"PUPPY","row":7,"col":4,"dRow":0,"dCol":-1},{"word":"LEAD","row":8,"col":3,"dRow":0,"dCol":1},{"word":"DOG","row":3,"col":0,"dRow":1,"dCol":0},{"word":"CAT","row":9,"col":5,"dRow":-1,"dCol":0},{"word":"VET","row":4,"col":7,"dRow":0,"dCol":1}],
  },
  {
    id: 'local-in-the-kitchen',
    topic: "In the Kitchen",
    topicSlug: 'in-the-kitchen',
    difficulty: 'hard',
    size: 10,
    grid: ["ATEGLSTFNE","ANRKLIANLE","IIWHISKTRN","NKTOASTERE","ANEGWETGAV","LIATKAKDPO","AFPTRKNISR","DEOGNAARFO","LETALPYFEK","ESPOONOEER"],
    words: [{"word":"TOASTER","row":3,"col":2,"dRow":0,"dCol":1},{"word":"KETTLE","row":5,"col":4,"dRow":-1,"dCol":1},{"word":"FRIDGE","row":8,"col":7,"dRow":-1,"dCol":0},{"word":"GRATER","row":7,"col":3,"dRow":-1,"dCol":1},{"word":"TEAPOT","row":3,"col":2,"dRow":1,"dCol":0},{"word":"SPOON","row":9,"col":1,"dRow":0,"dCol":1},{"word":"KNIFE","row":3,"col":1,"dRow":1,"dCol":0},{"word":"PLATE","row":8,"col":5,"dRow":0,"dCol":-1},{"word":"WHISK","row":2,"col":2,"dRow":0,"dCol":1},{"word":"LADLE","row":5,"col":0,"dRow":1,"dCol":0},{"word":"SINK","row":6,"col":8,"dRow":0,"dCol":-1},{"word":"OVEN","row":5,"col":9,"dRow":-1,"dCol":0},{"word":"TRAY","row":5,"col":3,"dRow":1,"dCol":1},{"word":"PAN","row":9,"col":2,"dRow":-1,"dCol":1}],
  },
  {
    id: 'local-clothes',
    topic: "Clothes",
    topicSlug: 'clothes',
    difficulty: 'hard',
    size: 10,
    grid: ["IOBOOTSASE","EISNAEJHOE","CLASVKECFN","BTROUSERSD","PKLCOSATCR","CGTKECRIEE","OORSSIBPDS","AAISKLMEOS","TAHSAUARLP","UCSCJACKET"],
    words: [{"word":"TROUSERS","row":3,"col":1,"dRow":0,"dCol":1},{"word":"JUMPER","row":9,"col":4,"dRow":-1,"dCol":1},{"word":"GLOVES","row":5,"col":1,"dRow":-1,"dCol":1},{"word":"JACKET","row":9,"col":4,"dRow":0,"dCol":1},{"word":"SOCKS","row":2,"col":3,"dRow":1,"dCol":0},{"word":"SCARF","row":6,"col":4,"dRow":-1,"dCol":1},{"word":"DRESS","row":3,"col":9,"dRow":1,"dCol":0},{"word":"SHIRT","row":9,"col":2,"dRow":-1,"dCol":0},{"word":"BOOTS","row":0,"col":2,"dRow":0,"dCol":1},{"word":"SKIRT","row":8,"col":3,"dRow":-1,"dCol":1},{"word":"JEANS","row":1,"col":6,"dRow":0,"dCol":-1},{"word":"COAT","row":5,"col":0,"dRow":1,"dCol":0},{"word":"BELT","row":6,"col":6,"dRow":1,"dCol":1},{"word":"HAT","row":8,"col":2,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-board-games',
    topic: "Board Games",
    topicSlug: 'board-games',
    difficulty: 'hard',
    size: 10,
    grid: ["CPCPUIMAET","ARLRERTRCR","RENNIWRAER","DCEUBETTIR","SIKRMONUPE","IDOISUADRN","EBTPOCNRSN","ALUCOLONDI","ICPLAYEREP","NESDCRULES"],
    words: [{"word":"COUNTER","row":7,"col":3,"dRow":-1,"dCol":1},{"word":"SPINNER","row":9,"col":9,"dRow":-1,"dCol":0},{"word":"PLAYER","row":8,"col":2,"dRow":0,"dCol":1},{"word":"WINNER","row":2,"col":5,"dRow":0,"dCol":-1},{"word":"BOARD","row":3,"col":4,"dRow":1,"dCol":1},{"word":"CARDS","row":0,"col":0,"dRow":1,"dCol":0},{"word":"SCORE","row":5,"col":4,"dRow":1,"dCol":1},{"word":"PIECE","row":4,"col":8,"dRow":-1,"dCol":0},{"word":"RULES","row":9,"col":5,"dRow":0,"dCol":1},{"word":"TOKEN","row":6,"col":2,"dRow":-1,"dCol":0},{"word":"TIMER","row":6,"col":2,"dRow":-1,"dCol":1},{"word":"DICE","row":5,"col":1,"dRow":-1,"dCol":0},{"word":"TURN","row":3,"col":6,"dRow":1,"dCol":1},{"word":"TEAM","row":0,"col":9,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-emotions',
    topic: "Emotions",
    topicSlug: 'emotions',
    difficulty: 'hard',
    size: 10,
    grid: ["PLILEAGERG","EUSUOIRUCB","EFGFRPAFYM","VEERDDTDLR","APXEDNEULF","ROHEPTFOIH","BHIHIYURSA","MLACOGLPEP","ORXJDNIKDP","DEXALERLEY"],
    words: [{"word":"GRATEFUL","row":0,"col":6,"dRow":1,"dCol":0},{"word":"CHEERFUL","row":7,"col":3,"dRow":-1,"dCol":0},{"word":"EXCITED","row":9,"col":1,"dRow":-1,"dCol":1},{"word":"CURIOUS","row":1,"col":8,"dRow":0,"dCol":-1},{"word":"HOPEFUL","row":6,"col":1,"dRow":-1,"dCol":0},{"word":"RELAXED","row":9,"col":6,"dRow":0,"dCol":-1},{"word":"JOYFUL","row":8,"col":3,"dRow":-1,"dCol":1},{"word":"HAPPY","row":5,"col":9,"dRow":1,"dCol":0},{"word":"PROUD","row":7,"col":7,"dRow":-1,"dCol":0},{"word":"EAGER","row":0,"col":4,"dRow":0,"dCol":1},{"word":"BRAVE","row":6,"col":0,"dRow":-1,"dCol":0},{"word":"SILLY","row":6,"col":8,"dRow":-1,"dCol":0},{"word":"CALM","row":7,"col":3,"dRow":0,"dCol":-1},{"word":"KIND","row":8,"col":7,"dRow":0,"dCol":-1}],
  },
  {
    id: 'local-bedtime',
    topic: "Bedtime",
    topicSlug: 'bedtime',
    difficulty: 'hard',
    size: 10,
    grid: ["PEELSBANNL","YRCURTAIND","JCYWSBPGPT","ANLRSMIHWE","MEAMSOLTLK","ATMATOLENN","SEPEONODWA","PTVRRLWDAL","EUYDYLYYYB","DKIGMTDLNU"],
    words: [{"word":"PYJAMAS","row":0,"col":0,"dRow":1,"dCol":0},{"word":"BLANKET","row":8,"col":9,"dRow":-1,"dCol":0},{"word":"CURTAIN","row":1,"col":2,"dRow":0,"dCol":1},{"word":"PILLOW","row":2,"col":6,"dRow":1,"dCol":0},{"word":"DUVET","row":9,"col":0,"dRow":-1,"dCol":1},{"word":"STORY","row":4,"col":4,"dRow":1,"dCol":0},{"word":"DREAM","row":8,"col":3,"dRow":-1,"dCol":0},{"word":"TEDDY","row":4,"col":7,"dRow":1,"dCol":0},{"word":"STARS","row":6,"col":0,"dRow":-1,"dCol":1},{"word":"NIGHT","row":0,"col":7,"dRow":1,"dCol":0},{"word":"SLEEP","row":0,"col":4,"dRow":0,"dCol":-1},{"word":"LAMP","row":3,"col":2,"dRow":1,"dCol":0},{"word":"YAWN","row":8,"col":8,"dRow":-1,"dCol":0},{"word":"MOON","row":3,"col":5,"dRow":1,"dCol":0}],
  },
  {
    id: 'local-the-seaside-town',
    topic: "The Seaside Town",
    topicSlug: 'the-seaside-town',
    difficulty: 'hard',
    size: 10,
    grid: ["HGCMYNYALI","BCICECREAM","JETFGKIOSK","EDANEMORPP","TADCORTOTI","TCFQHARUEE","YRLAOFJYAR","AALBROHCNA","URUOBRAHKQ","QYGEGATTOC"],
    words: [{"word":"PROMENADE","row":3,"col":8,"dRow":0,"dCol":-1},{"word":"ICECREAM","row":1,"col":2,"dRow":0,"dCol":1},{"word":"HARBOUR","row":8,"col":7,"dRow":0,"dCol":-1},{"word":"COTTAGE","row":9,"col":9,"dRow":0,"dCol":-1},{"word":"ARCADE","row":7,"col":1,"dRow":-1,"dCol":0},{"word":"ANCHOR","row":7,"col":9,"dRow":0,"dCol":-1},{"word":"FERRY","row":2,"col":3,"dRow":1,"dCol":1},{"word":"JETTY","row":2,"col":0,"dRow":1,"dCol":0},{"word":"BEACH","row":1,"col":0,"dRow":1,"dCol":1},{"word":"KIOSK","row":2,"col":5,"dRow":0,"dCol":1},{"word":"PIER","row":3,"col":9,"dRow":1,"dCol":0},{"word":"GULL","row":9,"col":2,"dRow":-1,"dCol":0},{"word":"BOAT","row":7,"col":3,"dRow":-1,"dCol":1},{"word":"QUAY","row":9,"col":0,"dRow":-1,"dCol":0}],
  },
  {
    id: 'local-rainy-day',
    topic: "Rainy Day",
    topicSlug: 'rainy-day',
    difficulty: 'hard',
    size: 10,
    grid: ["ELDDUPGRES","SEHIMROTSE","OHTEBICUSE","GSASROODNI","GHOWELLIES","YECCLOUDED","HLNELZZIRD","ITIDAMPIRD","NEAIHSALPS","HRRETTUGSG"],
    words: [{"word":"UMBRELLA","row":0,"col":4,"dRow":1,"dCol":0},{"word":"RAINCOAT","row":9,"col":2,"dRow":-1,"dCol":0},{"word":"WELLIES","row":4,"col":3,"dRow":0,"dCol":1},{"word":"DRIZZLE","row":6,"col":9,"dRow":0,"dCol":-1},{"word":"SHELTER","row":3,"col":1,"dRow":1,"dCol":0},{"word":"INDOORS","row":3,"col":9,"dRow":0,"dCol":-1},{"word":"PUDDLE","row":0,"col":5,"dRow":0,"dCol":-1},{"word":"SPLASH","row":8,"col":9,"dRow":0,"dCol":-1},{"word":"GUTTER","row":9,"col":7,"dRow":0,"dCol":-1},{"word":"CLOUD","row":5,"col":3,"dRow":0,"dCol":1},{"word":"STORM","row":1,"col":8,"dRow":0,"dCol":-1},{"word":"SOGGY","row":1,"col":0,"dRow":1,"dCol":0},{"word":"DAMP","row":7,"col":3,"dRow":0,"dCol":1},{"word":"DRIP","row":7,"col":9,"dRow":0,"dCol":-1}],
  },
];
