// GENERATED — do not edit by hand.
// Mirrors src/lib/wordSearchTopics.ts (the client's canonical list) so the
// nightly seeder can stock these pools without a client round trip. The two
// live in separate TypeScript projects that can't import across, hence the
// copy. Regenerate with the snippet in WORD_BANK_PLAN.md if the client list
// changes; duplicates that collapse to the same slug are dropped here.
export const SEED_TOPICS: string[] = [
  'Pop song titles',
  'Taylor Swift songs',
  'Music genres',
  'Musical instruments',
  'Concert and stage words',
  'Dance moves',
  'K-pop groups',
  'Music awards',
  'Singing and choir words',
  'Making a playlist',
  'Cat breeds',
  'Kitten care',
  'Cat behaviour',
  'Big cats of the world',
  'Dog breeds',
  'Baby animal names',
  'Ocean animals',
  'Rainforest animals',
  'Farm animals',
  'Birds in the backyard',
  'Bugs and insects',
  'Reptiles and amphibians',
  'Horses and riding',
  'Pet supplies',
  'Animals at the zoo',
  'Disney princesses',
  'Pixar movies',
  'Marvel superheroes',
  'Star Wars characters',
  'Disney villains',
  'Animated movie characters',
  'Superhero powers',
  'Fantasy creatures',
  'Anime favourites',
  'Movie theatre words',
  'Making a movie',
  'Binge-watching words',
  'Talent show words',
  'Video game characters',
  'Cross country running',
  'Track and field events',
  'Race day words',
  'Running shoes and gear',
  'Lacrosse gear',
  'Lacrosse positions',
  'Stretching and warm ups',
  'Coaching words',
  'Trophies and medals',
  'Relay races',
  'Team sports',
  'Olympic sports',
  'Soccer words',
  'Basketball words',
  'Swimming words',
  'Gymnastics',
  'Volleyball',
  'Winter sports',
  'Skateboarding',
  'Biking and BMX',
  'Tennis words',
  'Sports first aid',
  'School subjects',
  'Classroom supplies',
  'Library words',
  'Science lab equipment',
  'Math words',
  'Grammar words',
  'Geography words',
  'US states',
  'World capitals',
  'Ancient Egypt',
  'Ancient Rome',
  'The solar system',
  'Weather words',
  'Rocks and minerals',
  'Parts of the human body',
  'Plants and trees',
  'Famous inventors',
  'Coding words',
  'Recycling and the environment',
  'Field trip words',
  'Ice cream flavours',
  'Pizza toppings',
  'Breakfast foods',
  'Candy and sweets',
  'Fruits and vegetables',
  'Baking words',
  'Snack foods',
  'Food trucks',
  'Board games',
  'Art supplies',
  'Crafts and DIY',
  'Camping gear',
  'A day at the beach',
  'Summer vacation',
  'Amusement parks',
  'Birthday parties',
  'Halloween',
  'Winter holidays',
  'Emotions and feelings',
  'Friendship words',
  'Sleepover words',
  'Rainy day activities',
  'Road trip words',
  'Space travel',
  'Under the sea',
  'Dinosaurs',
  'Weather disasters',
  'Around the world',
  'Taylor Swift',
  'Olivia Rodrigo',
  'Sabrina Carpenter',
  'Ariana Grande',
  'Billie Eilish',
  'Chappell Roan',
  'Gracie Abrams',
  'Tate McRae',
  'Dua Lipa',
  'Katy Perry',
  'Demi Lovato',
  'Selena Gomez',
  'Star Wars',
  'Harry Potter',
  'Hunger Games',
  'Encanto',
  'Moana',
  'Frozen',
  'Wednesday Addams',
  'Avatar The Last Airbender',
  'Percy Jackson',
  'Bluey',
  'Miraculous Ladybug',
  'Descendants',
  'High School Musical',
  'The Baby-Sitters Club',
  'Gilmore Girls',
  'Stranger Things',
  'Gravity Falls',
  'The Owl House',
  'Zombies',
  'Amphibia',
  'Megan Trainor',
  'Baltimore Orioles',
  'Baltimore Ravens',
  'Baseball',
  'Football',
  'The NFL',
  'Major League Baseball',
  'The Olympics',
  'The World Cup',
  'Pro Soccer',
  'Minecraft',
  'Roblox',
  'Animal Crossing',
  'Stardew Valley',
  'LEGO',
  'LEGO Friends',
  'The Sims',
  'Wings of Fire',
  'Warriors Cats',
  'Diary of a Wimpy Kid',
  'Dork Diaries',
  'Percy Jackson Books',
  'Astronauts',
  'Planets',
  'Marine Biology',
  'Nail Art',
  'Fashion',
  'Photography',
  'Journaling',
  'Scrapbooking',
  'Disney Parks',
  'New York City',
  'Paris',
  'Broadway Musicals',
  'Slumber Parties',
  'Roller Skating',
  'Lacrosse',
  'Track and Field',
  'Cross Country',
  'Sprinting',
  'Long Jump',
  'Soccer',
  'Swimming',
  'Tennis',
  'Cheerleading',
  'Dance',
  'Dogs',
  'Cats',
  'Horses',
  'Wildlife',
  'Birds',
  'Butterflies',
  'Baby Animals',
  'Reptiles',
  'Sea Turtles',
  'Pandas',
];
