/** The vocabulary both word games are built from.
 *
 * This file is a build-time input, not shipped to the browser: the puzzles
 * it produces are baked into src/lib/*Puzzles.ts and that is all the app
 * ever loads. Keeping the pool here means every word in a generated puzzle
 * has already been vetted for "would a kid in this family know it?", so the
 * generators can fill grids freely without producing SCREE or OTIC.
 *
 * Five-letter words are deliberately not listed here — WORDLE_ANSWERS in
 * src/lib/wordleWords.ts is already a curated, family-safe list of exactly
 * that shape, and duplicating it would mean vetting the same words twice. */

export const THREE_LETTER = [
  'ace', 'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and',
  'ant', 'any', 'ape', 'arm', 'art', 'ash', 'ask', 'ate', 'axe', 'bad',
  'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'beg', 'bet', 'bid',
  'big', 'bin', 'bit', 'boa', 'bob', 'bog', 'bow', 'box', 'boy', 'bud',
  'bug', 'bun', 'bus', 'but', 'buy', 'cab', 'can', 'cap', 'car', 'cat',
  'cod', 'cog', 'cop', 'cot', 'cow', 'cry', 'cub', 'cue', 'cup', 'cut',
  'dad', 'dam', 'day', 'den', 'dew', 'did', 'dig', 'dim', 'dip', 'doe',
  'dog', 'dot', 'dry', 'due', 'dug', 'ear', 'eat', 'eel', 'egg', 'ego',
  'elf', 'elk', 'elm', 'end', 'eye', 'fan', 'far', 'fat', 'fed', 'fee',
  'few', 'fig', 'fin', 'fit', 'fix', 'fly', 'fog', 'for', 'fox', 'fry',
  'fun', 'fur', 'gap', 'gas', 'gem', 'get', 'gum', 'gun', 'gut', 'guy',
  'gym', 'had', 'ham', 'hat', 'hay', 'hen', 'her', 'hid', 'him', 'hip',
  'his', 'hit', 'hog', 'hop', 'hot', 'how', 'hub', 'hug', 'hum', 'hut',
  'ice', 'ill', 'ink', 'inn', 'ivy', 'jab', 'jam', 'jar', 'jaw', 'jet',
  'jog', 'jot', 'joy', 'jug', 'keg', 'key', 'kid', 'kit', 'lab', 'lad',
  'lap', 'law', 'lay', 'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'log',
  'lot', 'low', 'mad', 'man', 'map', 'mat', 'men', 'met', 'mix', 'mob',
  'mop', 'mud', 'mug', 'nap', 'net', 'new', 'nod', 'nor', 'not', 'now',
  'nut', 'oak', 'oar', 'oat', 'odd', 'off', 'oil', 'old', 'one', 'orb',
  'ore', 'our', 'out', 'owl', 'own', 'pad', 'pal', 'pan', 'paw', 'pay',
  'pea', 'peg', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'pod', 'pop',
  'pot', 'pro', 'pub', 'pug', 'pup', 'put', 'rag', 'ram', 'ran', 'rat',
  'raw', 'ray', 'red', 'rib', 'rid', 'rim', 'rip', 'rob', 'rod', 'rot',
  'row', 'rub', 'rug', 'rum', 'run', 'sad', 'sap', 'sat', 'saw', 'say',
  'sea', 'see', 'set', 'sew', 'she', 'shy', 'sip', 'sir', 'sit', 'six',
  'ski', 'sky', 'sly', 'sob', 'son', 'sow', 'soy', 'spa', 'spy', 'sty',
  'sub', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'tea',
  'ten', 'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top', 'toy',
  'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vet', 'vow', 'wag',
  'war', 'was', 'wax', 'way', 'web', 'wed', 'wet', 'who', 'why', 'wig',
  'win', 'wit', 'woe', 'wok', 'won', 'yak', 'yam', 'yap', 'yes', 'yet',
  'you', 'zip', 'zoo',
];

export const FOUR_LETTER = [
  'able', 'ache', 'acid', 'acre', 'aged', 'ahoy', 'aide', 'ajar', 'akin',
  'ally', 'aloe', 'also', 'alto', 'amid', 'ants', 'apex', 'arch', 'area',
  'arid', 'army', 'atom', 'aunt', 'auto', 'away', 'axis', 'babe', 'baby',
  'back', 'bail', 'bait', 'bake', 'bald', 'bale', 'ball', 'band', 'bang',
  'bank', 'barn', 'base', 'bash', 'bask', 'bath', 'bead', 'beak', 'beam',
  'bean', 'bear', 'beat', 'been', 'beef', 'beer', 'bell', 'belt', 'bend',
  'bent', 'best', 'bike', 'bill', 'bind', 'bird', 'bite', 'blew', 'blob',
  'blot', 'blow', 'blue', 'blur', 'boar', 'boat', 'body', 'boil', 'bold',
  'bolt', 'bomb', 'bone', 'book', 'boom', 'boot', 'bore', 'born', 'both',
  'bout', 'bowl', 'brag', 'bran', 'brim', 'brow', 'bulb', 'bulk', 'bull',
  'bump', 'bunk', 'buoy', 'burn', 'bush', 'busy', 'cafe', 'cage', 'cake',
  'calf', 'call', 'calm', 'came', 'camp', 'cane', 'cape', 'card', 'care',
  'cart', 'case', 'cash', 'cast', 'cave', 'cell', 'chat', 'chef', 'chew',
  'chin', 'chip', 'chop', 'city', 'clam', 'clap', 'claw', 'clay', 'clip',
  'clog', 'club', 'clue', 'coal', 'coat', 'code', 'coil', 'coin', 'cold',
  'colt', 'comb', 'come', 'cook', 'cool', 'cope', 'copy', 'cord', 'core',
  'cork', 'corn', 'cost', 'cosy', 'coop', 'cove', 'crab', 'crew', 'crib',
  'crop', 'crow', 'cube', 'cuff', 'cure', 'curl', 'cute', 'dare', 'dark',
  'dart', 'dash', 'data', 'date', 'dawn', 'days', 'dead', 'deaf', 'deal',
  'dean', 'dear', 'debt', 'deck', 'deed', 'deep', 'deer', 'dent', 'desk',
  'dial', 'dice', 'diet', 'dime', 'dine', 'dirt', 'dish', 'dive', 'dock',
  'does', 'dole', 'doll', 'dome', 'done', 'doom', 'door', 'dose', 'dove',
  'down', 'doze', 'drag', 'draw', 'drew', 'drip', 'drop', 'drum', 'duck',
  'dude', 'duel', 'dull', 'dumb', 'dune', 'dusk', 'dust', 'duty', 'each',
  'earl', 'earn', 'ease', 'east', 'easy', 'echo', 'edge', 'edit', 'else',
  'envy', 'epic', 'even', 'ever', 'evil', 'exam', 'exit', 'face', 'fact',
  'fade', 'fail', 'fair', 'fake', 'fall', 'fame', 'fang', 'farm', 'fast',
  'fate', 'fawn', 'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt',
  'fern', 'fest', 'file', 'fill', 'film', 'find', 'fine', 'fire', 'firm',
  'fish', 'fist', 'fits', 'five', 'flag', 'flap', 'flat', 'flea', 'fled',
  'flew', 'flex', 'flip', 'flow', 'foam', 'foil', 'fold', 'folk', 'fond',
  'font', 'food', 'fool', 'foot', 'ford', 'fork', 'form', 'fort', 'foul',
  'four', 'fowl', 'free', 'fret', 'frog', 'from', 'fuel', 'full', 'fume',
  'fund', 'fury', 'fuse', 'gain', 'gala', 'gale', 'game', 'gang', 'gate',
  'gave', 'gaze', 'gear', 'gene', 'gift', 'gild', 'gill', 'girl', 'give',
  'glad', 'glee', 'glen', 'glow', 'glue', 'goal', 'goat', 'gold', 'golf',
  'gone', 'good', 'gown', 'grab', 'gram', 'gray', 'grew', 'grid', 'grim',
  'grin', 'grip', 'grit', 'grow', 'gulf', 'gull', 'gust', 'hail', 'hair',
  'half', 'hall', 'halt', 'hand', 'hang', 'hard', 'hare', 'harm', 'harp',
  'hate', 'haul', 'have', 'hawk', 'haze', 'head', 'heal', 'heap', 'hear',
  'heat', 'heed', 'heel', 'held', 'helm', 'help', 'herb', 'herd', 'hero',
  'hide', 'high', 'hike', 'hill', 'hint', 'hire', 'hive', 'hold', 'hole',
  'holy', 'home', 'hone', 'hood', 'hoof', 'hook', 'hoop', 'hope', 'horn',
  'hose', 'host', 'hour', 'huge', 'hull', 'hung', 'hunt', 'hurl', 'hurt',
  'hush', 'husk', 'hymn', 'icon', 'idea', 'idle', 'inch', 'into', 'iron',
  'item', 'jade', 'jail', 'jazz', 'jeep', 'jest', 'jive', 'join', 'joke',
  'jolt', 'jump', 'june', 'junk', 'jury', 'just', 'keel', 'keen', 'keep',
  'kelp', 'kept', 'kick', 'kill', 'kilt', 'kind', 'king', 'kiss', 'kite',
  'knee', 'knew', 'knit', 'knob', 'knot', 'know', 'lace', 'lack', 'lady',
  'laid', 'lake', 'lamb', 'lame', 'lamp', 'land', 'lane', 'lard', 'lark',
  'lash', 'last', 'late', 'lawn', 'lazy', 'lead', 'leaf', 'leak', 'lean',
  'leap', 'left', 'lend', 'lens', 'lent', 'less', 'lice', 'lick', 'life',
  'lift', 'like', 'limb', 'lime', 'limp', 'line', 'link', 'lint', 'lion',
  'list', 'live', 'load', 'loaf', 'loan', 'lobe', 'lock', 'loft', 'logo',
  'lone', 'long', 'look', 'loom', 'loop', 'loot', 'lord', 'lore', 'lose',
  'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'lure', 'lush',
  'lute', 'made', 'maid', 'mail', 'main', 'make', 'male', 'mall', 'malt',
  'mane', 'many', 'maple', 'mare', 'mark', 'mash', 'mask', 'mass', 'mast',
  'mate', 'math', 'maze', 'mead', 'meal', 'mean', 'meat', 'meek', 'meet',
  'melt', 'mend', 'menu', 'mere', 'mesh', 'mess', 'mice', 'mild', 'mile',
  'milk', 'mill', 'mind', 'mine', 'mint', 'miss', 'mist', 'moat', 'mock',
  'mode', 'mold', 'mole', 'monk', 'mood', 'moon', 'moor', 'more', 'moss',
  'most', 'moth', 'move', 'much', 'mule', 'mush', 'must', 'mute', 'myth',
  'nail', 'name', 'nape', 'navy', 'near', 'neat', 'neck', 'need', 'nest',
  'news', 'next', 'nice', 'nine', 'node', 'none', 'noon', 'norm', 'nose',
  'note', 'noun', 'oath', 'obey', 'odds', 'omit', 'once', 'only', 'onto',
  'open', 'oval', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pail',
  'pain', 'pair', 'pale', 'palm', 'pane', 'pant', 'park', 'part', 'pass',
  'past', 'path', 'pave', 'pawn', 'peak', 'peal', 'pear', 'peat', 'peck',
  'peel', 'peer', 'pelt', 'perk', 'pest', 'pick', 'pier', 'pile', 'pill',
  'pine', 'pink', 'pint', 'pipe', 'pity', 'plan', 'play', 'plea', 'plot',
  'plow', 'plug', 'plum', 'plus', 'poem', 'poet', 'pole', 'poll', 'pond',
  'pony', 'pool', 'poor', 'pope', 'pork', 'port', 'pose', 'post', 'pour',
  'pray', 'prey', 'prop', 'pull', 'pulp', 'pump', 'punk', 'pure', 'push',
  'quit', 'quiz', 'race', 'rack', 'raft', 'rage', 'raid', 'rail', 'rain',
  'rake', 'ramp', 'rang', 'rank', 'rant', 'rare', 'rash', 'rate', 'rave',
  'read', 'real', 'reap', 'rear', 'reed', 'reef', 'reel', 'rely', 'rent',
  'rest', 'ribs', 'rice', 'rich', 'ride', 'rift', 'rile', 'rind', 'ring',
  'rink', 'riot', 'ripe', 'rise', 'risk', 'road', 'roam', 'roar', 'robe',
  'rock', 'rode', 'role', 'roll', 'roof', 'rook', 'room', 'root', 'rope',
  'rose', 'rosy', 'rout', 'ruby', 'rude', 'ruin', 'rule', 'rung', 'runt',
  'rush', 'rust', 'sack', 'safe', 'sage', 'said', 'sail', 'sake', 'salt',
  'same', 'sand', 'sane', 'sang', 'sank', 'save', 'scan', 'scar', 'seal',
  'seam', 'seat', 'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send',
  'sent', 'shed', 'shin', 'ship', 'shoe', 'shop', 'shot', 'show', 'shut',
  'sick', 'side', 'sigh', 'sign', 'silk', 'sill', 'silo', 'sing', 'sink',
  'site', 'size', 'skin', 'skip', 'skit', 'slab', 'slam', 'slap', 'sled',
  'slid', 'slim', 'slip', 'slit', 'slot', 'slow', 'slug', 'smog', 'snap',
  'snip', 'snow', 'snug', 'soak', 'soap', 'soar', 'sock', 'soda', 'sofa',
  'soft', 'soil', 'sold', 'sole', 'solo', 'some', 'song', 'soon', 'soot',
  'sore', 'sort', 'soul', 'soup', 'sour', 'span', 'spin', 'spit', 'spot',
  'spun', 'spur', 'stag', 'star', 'stay', 'stem', 'step', 'stew', 'stir',
  'stop', 'stow', 'stub', 'stun', 'such', 'suit', 'sung', 'sunk', 'sure',
  'surf', 'swam', 'swan', 'swap', 'sway', 'swim', 'tack', 'tail', 'take',
  'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'task', 'taut', 'teak',
  'teal', 'team', 'tear', 'tech', 'teem', 'tell', 'tend', 'tent', 'term',
  'test', 'text', 'than', 'that', 'thaw', 'thee', 'them', 'then', 'they',
  'thin', 'this', 'thud', 'thus', 'tick', 'tide', 'tidy', 'tier', 'tile',
  'till', 'tilt', 'time', 'tint', 'tiny', 'tire', 'toad', 'toil', 'told',
  'toll', 'tomb', 'tone', 'took', 'tool', 'toot', 'torn', 'toss', 'tour',
  'town', 'trap', 'tray', 'tree', 'trek', 'trim', 'trio', 'trip', 'trot',
  'true', 'tuba', 'tube', 'tuck', 'tuna', 'tune', 'turf', 'turn', 'twig',
  'twin', 'type', 'ugly', 'unit', 'upon', 'urge', 'used', 'user', 'vain',
  'vane', 'vase', 'vast', 'veal', 'veil', 'vein', 'vent', 'verb', 'very',
  'vest', 'veto', 'vibe', 'vice', 'view', 'vine', 'visa', 'void', 'volt',
  'vote', 'wade', 'wage', 'wail', 'wait', 'wake', 'walk', 'wall', 'wand',
  'want', 'ward', 'warm', 'warn', 'warp', 'wart', 'wash', 'wasp', 'wave',
  'wavy', 'weak', 'wean', 'wear', 'weed', 'week', 'weep', 'weld', 'well',
  'went', 'were', 'west', 'what', 'when', 'whip', 'whom', 'wick', 'wide',
  'wife', 'wild', 'will', 'wilt', 'wind', 'wine', 'wing', 'wink', 'wipe',
  'wire', 'wise', 'wish', 'wisp', 'with', 'woke', 'wolf', 'wood', 'wool',
  'word', 'wore', 'work', 'worm', 'worn', 'wove', 'wrap', 'yard', 'yarn',
  'yawn', 'year', 'yell', 'yoga', 'yolk', 'your', 'zeal', 'zero', 'zone',
  'zoom',
];

/** Extra five-letter words, on top of WORDLE_ANSWERS.
 *
 * The crossword fill needs these. Its 5x5 pattern leaves three full rows
 * and a column of five crossing each other, and how many grids exist at all
 * scales steeply with vocabulary: on WORDLE_ANSWERS alone the solver found
 * two in a minute, because nearly every partial fill dead-ends. These are
 * the ordinary words that list happens to exclude — it bars plurals ending
 * in S (a fair rule for a Wordle answer, meaningless for a crossword) and
 * leans away from verb forms. */
export const FIVE_LETTER_EXTRA = [
  'acres', 'actor', 'acute', 'aired', 'alarm', 'album', 'alert', 'alike',
  'amber', 'ample', 'ankle', 'apart', 'apple', 'apron', 'areas', 'armed',
  'aroma', 'ashes', 'aside', 'asked', 'atlas', 'attic', 'bacon', 'badge',
  'bags', 'baked', 'balls', 'bands', 'banks', 'barns', 'based', 'bases',
  'beads', 'beams', 'beans', 'bears', 'beats', 'beers', 'bells', 'belts',
  'bends', 'bikes', 'birds', 'blame', 'blank', 'blast', 'blaze', 'blend',
  'blink', 'blocks', 'bloom', 'blown', 'blues', 'boats', 'bonds', 'bones',
  'books', 'boots', 'bored', 'bowls', 'boxes', 'brain', 'brake', 'brass',
  'brave', 'bread', 'break', 'brick', 'bride', 'brief', 'bring', 'broke',
  'brush', 'bunch', 'burns', 'buses', 'cabin', 'cable', 'cakes', 'calls',
  'calms', 'camel', 'camps', 'candy', 'canoe', 'cards', 'cares', 'carts',
  'carve', 'cases', 'casts', 'catch', 'caves', 'chain', 'chair', 'chalk',
  'charm', 'chase', 'cheap', 'check', 'cheer', 'chess', 'chest', 'chief',
  'child', 'chips', 'chose', 'claim', 'clams', 'clean', 'clear', 'clerk',
  'climb', 'clips', 'clock', 'close', 'cloth', 'cloud', 'clubs', 'coach',
  'coals', 'coast', 'coats', 'coins', 'cooks', 'cools', 'coral', 'cords',
  'costs', 'couch', 'could', 'count', 'court', 'cover', 'crabs', 'crack',
  'craft', 'crane', 'crash', 'crawl', 'cream', 'crept', 'crews', 'crops',
  'cross', 'crowd', 'crown', 'crumb', 'crush', 'cubes', 'cured', 'curls',
  'curve', 'cycle', 'dares', 'dates', 'deals', 'dealt', 'dears', 'decks',
  'deeds', 'deals', 'dense', 'depth', 'desks', 'dimes', 'dines', 'dirty',
  'dishes', 'ditch', 'dived', 'dives', 'docks', 'dolls', 'domes', 'doors',
  'doubt', 'dough', 'doves', 'dozen', 'drags', 'drain', 'drank', 'drawn',
  'draws', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive',
  'drops', 'drove', 'drums', 'ducks', 'dunes', 'dusty', 'eagle', 'early',
  'earns', 'earth', 'eaten', 'edges', 'eight', 'elbow', 'empty', 'ended',
  'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every',
  'exact', 'extra', 'faces', 'facts', 'faded', 'fails', 'faint', 'fairs',
  'faith', 'falls', 'false', 'fancy', 'farms', 'fears', 'feast', 'feeds',
  'feels', 'fence', 'ferry', 'fever', 'field', 'fifth', 'fight', 'files',
  'fills', 'films', 'final', 'finds', 'fines', 'fired', 'fires', 'first',
  'fists', 'flags', 'flame', 'flash', 'fleet', 'flies', 'float', 'flock',
  'flood', 'floor', 'flour', 'flows', 'fluid', 'flute', 'foams', 'folds',
  'folks', 'foods', 'fools', 'force', 'forks', 'forms', 'forth', 'found',
  'frame', 'fresh', 'front', 'frost', 'fruit', 'fumes', 'funds', 'games',
  'gates', 'gazes', 'gears', 'ghost', 'giant', 'gifts', 'girls', 'given',
  'gives', 'glass', 'globe', 'glove', 'glows', 'goals', 'goats', 'going',
  'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grass',
  'grave', 'great', 'green', 'greet', 'grill', 'grins', 'grips', 'group',
  'grown', 'grows', 'guard', 'guess', 'guest', 'guide', 'habit', 'hairs',
  'halls', 'hands', 'hangs', 'happy', 'harsh', 'hatch', 'hates', 'heads',
  'heals', 'heaps', 'heard', 'heart', 'heats', 'heavy', 'hedge', 'heels',
  'helps', 'herbs', 'hides', 'hills', 'hints', 'hired', 'hives', 'holds',
  'holes', 'homes', 'honey', 'hoods', 'hooks', 'hoped', 'hopes', 'horns',
  'horse', 'hoses', 'hotel', 'hours', 'house', 'human', 'hunts', 'hurry',
  'ideal', 'ideas', 'image', 'index', 'inner', 'input', 'irons', 'issue',
  'items', 'jeans', 'jewel', 'joins', 'jokes', 'judge', 'juice', 'jumps',
  'keeps', 'kicks', 'kinds', 'kings', 'kites', 'knees', 'knife', 'knock',
  'knots', 'known', 'knows', 'label', 'lacks', 'lakes', 'lambs', 'lamps',
  'lands', 'lanes', 'large', 'lasts', 'later', 'laugh', 'lawns', 'layer',
  'leads', 'leaks', 'leans', 'leaps', 'learn', 'lease', 'least', 'leave',
  'legal', 'lemon', 'level', 'light', 'limbs', 'limit', 'lines', 'links',
  'lions', 'lists', 'lived', 'lives', 'loads', 'loans', 'local', 'locks',
  'lodge', 'logic', 'looks', 'loops', 'loose', 'lords', 'loses', 'loved',
  'loves', 'lower', 'lucky', 'lunch', 'lungs', 'magic', 'major', 'maker',
  'males', 'maple', 'march', 'marks', 'marsh', 'masks', 'match', 'meals',
  'means', 'meant', 'meats', 'medal', 'meets', 'melts', 'metal', 'meter',
  'might', 'miles', 'mills', 'minds', 'mines', 'minor', 'mixed', 'model',
  'moist', 'moles', 'money', 'month', 'moods', 'moons', 'moral', 'motor',
  'mount', 'mouse', 'mouth', 'moved', 'moves', 'movie', 'music', 'nails',
  'names', 'necks', 'needs', 'nerve', 'nests', 'never', 'newer', 'night',
  'noble', 'noise', 'north', 'notes', 'novel', 'nurse', 'oaths', 'ocean',
  'offer', 'often', 'olive', 'onion', 'opens', 'opera', 'orbit', 'order',
  'organ', 'other', 'otter', 'ounce', 'outer', 'owner', 'packs', 'pages',
  'pails', 'pains', 'paint', 'pairs', 'palms', 'panel', 'panic', 'pants',
  'paper', 'parks', 'parts', 'party', 'paste', 'patch', 'paths', 'pause',
  'peace', 'peach', 'pearl', 'pears', 'pedal', 'peels', 'penny', 'phase',
  'phone', 'photo', 'piano', 'picks', 'piece', 'piles', 'pilot', 'pines',
  'pipes', 'pitch', 'pizza', 'place', 'plain', 'plane', 'plans', 'plant',
  'plate', 'plays', 'plots', 'plugs', 'poems', 'point', 'poles', 'ponds',
  'pools', 'porch', 'ports', 'pound', 'power', 'press', 'price', 'pride',
  'print', 'prize', 'proof', 'proud', 'prove', 'pulls', 'pumps', 'punch',
  'pupil', 'puppy', 'quick', 'quiet', 'quilt', 'quite', 'races', 'racks',
  'radio', 'rails', 'rains', 'raise', 'rally', 'ranch', 'range', 'ranks',
  'rapid', 'rates', 'reach', 'reads', 'ready', 'realm', 'rebel', 'reeds',
  'reefs', 'reels', 'refer', 'relax', 'rents', 'reply', 'rests', 'rider',
  'rides', 'ridge', 'right', 'rings', 'rinks', 'risen', 'rises', 'risks',
  'rival', 'river', 'roads', 'roast', 'robes', 'robin', 'robot', 'rocks',
  'rocky', 'roles', 'rolls', 'roofs', 'rooms', 'roots', 'ropes', 'roses',
  'rough', 'round', 'route', 'royal', 'ruins', 'rules', 'rural', 'sails',
  'saint', 'salad', 'sales', 'sandy', 'sauce', 'scale', 'scarf', 'scene',
  'scent', 'scope', 'score', 'scout', 'seals', 'seams', 'seats', 'seeds',
  'seeks', 'seems', 'sells', 'sends', 'sense', 'serve', 'seven', 'shade',
  'shake', 'shall', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shiny', 'ships', 'shirt', 'shock',
  'shoes', 'shops', 'shore', 'short', 'shots', 'shout', 'shown', 'shows',
  'sides', 'sight', 'signs', 'silly', 'since', 'sings', 'sinks', 'sites',
  'sixth', 'sizes', 'skate', 'skill', 'skins', 'skirt', 'slabs', 'sleep',
  'slept', 'slice', 'slide', 'slope', 'slots', 'small', 'smart', 'smell',
  'smile', 'smoke', 'snack', 'snake', 'snaps', 'solar', 'solid', 'solve',
  'songs', 'sorry', 'sorts', 'sound', 'south', 'space', 'spare', 'spark',
  'speak', 'speed', 'spell', 'spend', 'spent', 'spice', 'spill', 'spine',
  'split', 'spoke', 'spoon', 'sport', 'spots', 'spray', 'squad', 'stack',
  'staff', 'stage', 'stair', 'stake', 'stale', 'stamp', 'stand', 'stare',
  'stars', 'start', 'state', 'stays', 'steam', 'steel', 'steep', 'stems',
  'steps', 'stick', 'stiff', 'still', 'stock', 'stone', 'stood', 'stool',
  'stops', 'store', 'storm', 'story', 'stove', 'strap', 'straw', 'strip',
  'stuck', 'study', 'stuff', 'style', 'sugar', 'suits', 'sunny', 'super',
  'sweet', 'swept', 'swift', 'swims', 'swing', 'table', 'tails', 'taken',
  'takes', 'tales', 'talks', 'tanks', 'tapes', 'tasks', 'taste', 'tasty',
  'teach', 'teams', 'tears', 'teeth', 'tells', 'tends', 'tents', 'terms',
  'tests', 'thank', 'their', 'theme', 'there', 'these', 'thick', 'thief',
  'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw', 'throw',
  'thumb', 'tides', 'tiger', 'tight', 'tiles', 'timer', 'times', 'tired',
  'title', 'toast', 'today', 'token', 'tones', 'tools', 'tooth', 'topic',
  'torch', 'total', 'touch', 'tough', 'tours', 'towel', 'tower', 'towns',
  'trace', 'track', 'trade', 'trail', 'train', 'traps', 'trash', 'trays',
  'treat', 'trees', 'trend', 'trial', 'tribe', 'trick', 'tried', 'trips',
  'truck', 'trunk', 'trust', 'truth', 'tubes', 'tulip', 'tunes', 'turns',
  'twice', 'twigs', 'twins', 'twist', 'uncle', 'under', 'union', 'unite',
  'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'value', 'vault',
  'veins', 'verbs', 'video', 'views', 'vines', 'virus', 'visit', 'vital',
  'vivid', 'vocal', 'voice', 'votes', 'vowel', 'wagon', 'waist', 'waits',
  'wakes', 'walks', 'walls', 'wants', 'wards', 'warms', 'warns', 'waste',
  'watch', 'water', 'waves', 'weeds', 'weeks', 'weigh', 'weird', 'wells',
  'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'winds', 'wines', 'wings', 'wipes', 'wires', 'witch', 'woman',
  'woods', 'words', 'works', 'world', 'worms', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrist', 'write', 'wrong', 'wrote', 'yacht',
  'yards', 'yarns', 'years', 'yield', 'young', 'youth', 'zebra', 'zones',
];

/** Six- and seven-letter words that make good Word Bloom bases: common
 * enough to recognise, and with a letter mix that yields a decent haul of
 * shorter words. */
export const BLOOM_BASES = [
  'animal', 'basket', 'branch', 'bottle', 'camera', 'candle', 'carpet',
  'castle', 'cellar', 'circle', 'closet', 'coffee', 'colour', 'corner',
  'cotton', 'crayon', 'dinner', 'dragon', 'engine', 'family', 'farmer',
  'father', 'finger', 'flower', 'forest', 'friend', 'garden', 'guitar',
  'hamster', 'harvest', 'insect', 'island', 'jacket', 'jungle', 'kitten',
  'ladder', 'lantern', 'listen', 'market', 'meadow', 'monster', 'morning',
  'mother', 'napkin', 'orange', 'packet', 'pantry', 'parcel', 'parent',
  'pencil', 'picnic', 'pirate', 'planet', 'pocket', 'pumpkin', 'puppet',
  'rabbit', 'rocket', 'sailor', 'saddle', 'school', 'silver', 'singer',
  'sister', 'skater', 'spider', 'spring', 'stable', 'summer', 'sunset',
  'temple', 'tiger', 'travel', 'tunnel', 'turtle', 'valley', 'violet',
  'wagon', 'walnut', 'wander', 'window', 'winter', 'wizard', 'yellow',
];
