/** The vocabulary both word games are built from.
 *
 * This file is a build-time input, not shipped to the browser: the puzzles
 * it produces are baked into src/lib/*Puzzles.ts and that is all the app
 * ever loads. Keeping the pool here means every word in a generated puzzle
 * has already been vetted for "would a kid in this family know it?", so the
 * generators can fill grids freely without producing SCREE or OTIC.
 *
 * Five-letter words are deliberately not listed here — WORDLE_ANSWERS in
 * src/lib/wordleWords.ts is already a curated, family-safe list of exactly
 * that shape, and duplicating it would mean vetting the same words twice. */

export const THREE_LETTER = [
  'ace', 'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and',
  'ant', 'any', 'ape', 'arm', 'art', 'ash', 'ask', 'ate', 'axe', 'bad',
  'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'beg', 'bet', 'bid',
  'big', 'bin', 'bit', 'boa', 'bob', 'bog', 'bow', 'box', 'boy', 'bud',
  'bug', 'bun', 'bus', 'but', 'buy', 'cab', 'can', 'cap', 'car', 'cat',
  'cod', 'cog', 'cop', 'cot', 'cow', 'cry', 'cub', 'cue', 'cup', 'cut',
  'dad', 'dam', 'day', 'den', 'dew', 'did', 'dig', 'dim', 'dip', 'doe',
  'dog', 'dot', 'dry', 'due', 'dug', 'ear', 'eat', 'eel', 'egg', 'ego',
  'elf', 'elk', 'elm', 'end', 'eye', 'fan', 'far', 'fat', 'fed', 'fee',
  'few', 'fig', 'fin', 'fit', 'fix', 'fly', 'fog', 'for', 'fox', 'fry',
  'fun', 'fur', 'gap', 'gas', 'gem', 'get', 'gum', 'gun', 'gut', 'guy',
  'gym', 'had', 'ham', 'hat', 'hay', 'hen', 'her', 'hid', 'him', 'hip',
  'his', 'hit', 'hog', 'hop', 'hot', 'how', 'hub', 'hug', 'hum', 'hut',
  'ice', 'ill', 'ink', 'inn', 'ivy', 'jab', 'jam', 'jar', 'jaw', 'jet',
  'jog', 'jot', 'joy', 'jug', 'keg', 'key', 'kid', 'kit', 'lab', 'lad',
  'lap', 'law', 'lay', 'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'log',
  'lot', 'low', 'mad', 'man', 'map', 'mat', 'men', 'met', 'mix', 'mob',
  'mop', 'mud', 'mug', 'nap', 'net', 'new', 'nod', 'nor', 'not', 'now',
  'nut', 'oak', 'oar', 'oat', 'odd', 'off', 'oil', 'old', 'one', 'orb',
  'ore', 'our', 'out', 'owl', 'own', 'pad', 'pal', 'pan', 'paw', 'pay',
  'pea', 'peg', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'pod', 'pop',
  'pot', 'pro', 'pub', 'pug', 'pup', 'put', 'rag', 'ram', 'ran', 'rat',
  'raw', 'ray', 'red', 'rib', 'rid', 'rim', 'rip', 'rob', 'rod', 'rot',
  'row', 'rub', 'rug', 'rum', 'run', 'sad', 'sap', 'sat', 'saw', 'say',
  'sea', 'see', 'set', 'sew', 'she', 'shy', 'sip', 'sir', 'sit', 'six',
  'ski', 'sky', 'sly', 'sob', 'son', 'sow', 'soy', 'spa', 'spy', 'sty',
  'sub', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'tea',
  'ten', 'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top', 'toy',
  'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vet', 'vow', 'wag',
  'war', 'was', 'wax', 'way', 'web', 'wed', 'wet', 'who', 'why', 'wig',
  'win', 'wit', 'woe', 'wok', 'won', 'yak', 'yam', 'yap', 'yes', 'yet',
  'you', 'zip', 'zoo',
];

export const FOUR_LETTER = [
  'able', 'ache', 'acid', 'acre', 'aged', 'ahoy', 'aide', 'ajar', 'akin',
  'ally', 'aloe', 'also', 'alto', 'amid', 'ants', 'apex', 'arch', 'area',
  'arid', 'army', 'atom', 'aunt', 'auto', 'away', 'axis', 'babe', 'baby',
  'back', 'bail', 'bait', 'bake', 'bald', 'bale', 'ball', 'band', 'bang',
  'bank', 'barn', 'base', 'bash', 'bask', 'bath', 'bead', 'beak', 'beam',
  'bean', 'bear', 'beat', 'been', 'beef', 'beer', 'bell', 'belt', 'bend',
  'bent', 'best', 'bike', 'bill', 'bind', 'bird', 'bite', 'blew', 'blob',
  'blot', 'blow', 'blue', 'blur', 'boar', 'boat', 'body', 'boil', 'bold',
  'bolt', 'bomb', 'bone', 'book', 'boom', 'boot', 'bore', 'born', 'both',
  'bout', 'bowl', 'brag', 'bran', 'brim', 'brow', 'bulb', 'bulk', 'bull',
  'bump', 'bunk', 'buoy', 'burn', 'bush', 'busy', 'cafe', 'cage', 'cake',
  'calf', 'call', 'calm', 'came', 'camp', 'cane', 'cape', 'card', 'care',
  'cart', 'case', 'cash', 'cast', 'cave', 'cell', 'chat', 'chef', 'chew',
  'chin', 'chip', 'chop', 'city', 'clam', 'clap', 'claw', 'clay', 'clip',
  'clog', 'club', 'clue', 'coal', 'coat', 'code', 'coil', 'coin', 'cold',
  'colt', 'comb', 'come', 'cook', 'cool', 'cope', 'copy', 'cord', 'core',
  'cork', 'corn', 'cost', 'cosy', 'coop', 'cove', 'crab', 'crew', 'crib',
  'crop', 'crow', 'cube', 'cuff', 'cure', 'curl', 'cute', 'dare', 'dark',
  'dart', 'dash', 'data', 'date', 'dawn', 'days', 'dead', 'deaf', 'deal',
  'dean', 'dear', 'debt', 'deck', 'deed', 'deep', 'deer', 'dent', 'desk',
  'dial', 'dice', 'diet', 'dime', 'dine', 'dirt', 'dish', 'dive', 'dock',
  'does', 'dole', 'doll', 'dome', 'done', 'doom', 'door', 'dose', 'dove',
  'down', 'doze', 'drag', 'draw', 'drew', 'drip', 'drop', 'drum', 'duck',
  'dude', 'duel', 'dull', 'dumb', 'dune', 'dusk', 'dust', 'duty', 'each',
  'earl', 'earn', 'ease', 'east', 'easy', 'echo', 'edge', 'edit', 'else',
  'envy', 'epic', 'even', 'ever', 'evil', 'exam', 'exit', 'face', 'fact',
  'fade', 'fail', 'fair', 'fake', 'fall', 'fame', 'fang', 'farm', 'fast',
  'fate', 'fawn', 'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt',
  'fern', 'fest', 'file', 'fill', 'film', 'find', 'fine', 'fire', 'firm',
  'fish', 'fist', 'fits', 'five', 'flag', 'flap', 'flat', 'flea', 'fled',
  'flew', 'flex', 'flip', 'flow', 'foam', 'foil', 'fold', 'folk', 'fond',
  'font', 'food', 'fool', 'foot', 'ford', 'fork', 'form', 'fort', 'foul',
  'four', 'fowl', 'free', 'fret', 'frog', 'from', 'fuel', 'full', 'fume',
  'fund', 'fury', 'fuse', 'gain', 'gala', 'gale', 'game', 'gang', 'gate',
  'gave', 'gaze', 'gear', 'gene', 'gift', 'gild', 'gill', 'girl', 'give',
  'glad', 'glee', 'glen', 'glow', 'glue', 'goal', 'goat', 'gold', 'golf',
  'gone', 'good', 'gown', 'grab', 'gram', 'gray', 'grew', 'grid', 'grim',
  'grin', 'grip', 'grit', 'grow', 'gulf', 'gull', 'gust', 'hail', 'hair',
  'half', 'hall', 'halt', 'hand', 'hang', 'hard', 'hare', 'harm', 'harp',
  'hate', 'haul', 'have', 'hawk', 'haze', 'head', 'heal', 'heap', 'hear',
  'heat', 'heed', 'heel', 'held', 'helm', 'help', 'herb', 'herd', 'hero',
  'hide', 'high', 'hike', 'hill', 'hint', 'hire', 'hive', 'hold', 'hole',
  'holy', 'home', 'hone', 'hood', 'hoof', 'hook', 'hoop', 'hope', 'horn',
  'hose', 'host', 'hour', 'huge', 'hull', 'hung', 'hunt', 'hurl', 'hurt',
  'hush', 'husk', 'hymn', 'icon', 'idea', 'idle', 'inch', 'into', 'iron',
  'item', 'jade', 'jail', 'jazz', 'jeep', 'jest', 'jive', 'join', 'joke',
  'jolt', 'jump', 'june', 'junk', 'jury', 'just', 'keel', 'keen', 'keep',
  'kelp', 'kept', 'kick', 'kill', 'kilt', 'kind', 'king', 'kiss', 'kite',
  'knee', 'knew', 'knit', 'knob', 'knot', 'know', 'lace', 'lack', 'lady',
  'laid', 'lake', 'lamb', 'lame', 'lamp', 'land', 'lane', 'lard', 'lark',
  'lash', 'last', 'late', 'lawn', 'lazy', 'lead', 'leaf', 'leak', 'lean',
  'leap', 'left', 'lend', 'lens', 'lent', 'less', 'lice', 'lick', 'life',
  'lift', 'like', 'limb', 'lime', 'limp', 'line', 'link', 'lint', 'lion',
  'list', 'live', 'load', 'loaf', 'loan', 'lobe', 'lock', 'loft', 'logo',
  'lone', 'long', 'look', 'loom', 'loop', 'loot', 'lord', 'lore', 'lose',
  'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'lure', 'lush',
  'lute', 'made', 'maid', 'mail', 'main', 'make', 'male', 'mall', 'malt',
  'mane', 'many', 'maple', 'mare', 'mark', 'mash', 'mask', 'mass', 'mast',
  'mate', 'math', 'maze', 'mead', 'meal', 'mean', 'meat', 'meek', 'meet',
  'melt', 'mend', 'menu', 'mere', 'mesh', 'mess', 'mice', 'mild', 'mile',
  'milk', 'mill', 'mind', 'mine', 'mint', 'miss', 'mist', 'moat', 'mock',
  'mode', 'mold', 'mole', 'monk', 'mood', 'moon', 'moor', 'more', 'moss',
  'most', 'moth', 'move', 'much', 'mule', 'mush', 'must', 'mute', 'myth',
  'nail', 'name', 'nape', 'navy', 'near', 'neat', 'neck', 'need', 'nest',
  'news', 'next', 'nice', 'nine', 'node', 'none', 'noon', 'norm', 'nose',
  'note', 'noun', 'oath', 'obey', 'odds', 'omit', 'once', 'only', 'onto',
  'open', 'oval', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pail',
  'pain', 'pair', 'pale', 'palm', 'pane', 'pant', 'park', 'part', 'pass',
  'past', 'path', 'pave', 'pawn', 'peak', 'peal', 'pear', 'peat', 'peck',
  'peel', 'peer', 'pelt', 'perk', 'pest', 'pick', 'pier', 'pile', 'pill',
  'pine', 'pink', 'pint', 'pipe', 'pity', 'plan', 'play', 'plea', 'plot',
  'plow', 'plug', 'plum', 'plus', 'poem', 'poet', 'pole', 'poll', 'pond',
  'pony', 'pool', 'poor', 'pope', 'pork', 'port', 'pose', 'post', 'pour',
  'pray', 'prey', 'prop', 'pull', 'pulp', 'pump', 'punk', 'pure', 'push',
  'quit', 'quiz', 'race', 'rack', 'raft', 'rage', 'raid', 'rail', 'rain',
  'rake', 'ramp', 'rang', 'rank', 'rant', 'rare', 'rash', 'rate', 'rave',
  'read', 'real', 'reap', 'rear', 'reed', 'reef', 'reel', 'rely', 'rent',
  'rest', 'ribs', 'rice', 'rich', 'ride', 'rift', 'rile', 'rind', 'ring',
  'rink', 'riot', 'ripe', 'rise', 'risk', 'road', 'roam', 'roar', 'robe',
  'rock', 'rode', 'role', 'roll', 'roof', 'rook', 'room', 'root', 'rope',
  'rose', 'rosy', 'rout', 'ruby', 'rude', 'ruin', 'rule', 'rung', 'runt',
  'rush', 'rust', 'sack', 'safe', 'sage', 'said', 'sail', 'sake', 'salt',
  'same', 'sand', 'sane', 'sang', 'sank', 'save', 'scan', 'scar', 'seal',
  'seam', 'seat', 'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send',
  'sent', 'shed', 'shin', 'ship', 'shoe', 'shop', 'shot', 'show', 'shut',
  'sick', 'side', 'sigh', 'sign', 'silk', 'sill', 'silo', 'sing', 'sink',
  'site', 'size', 'skin', 'skip', 'skit', 'slab', 'slam', 'slap', 'sled',
  'slid', 'slim', 'slip', 'slit', 'slot', 'slow', 'slug', 'smog', 'snap',
  'snip', 'snow', 'snug', 'soak', 'soap', 'soar', 'sock', 'soda', 'sofa',
  'soft', 'soil', 'sold', 'sole', 'solo', 'some', 'song', 'soon', 'soot',
  'sore', 'sort', 'soul', 'soup', 'sour', 'span', 'spin', 'spit', 'spot',
  'spun', 'spur', 'stag', 'star', 'stay', 'stem', 'step', 'stew', 'stir',
  'stop', 'stow', 'stub', 'stun', 'such', 'suit', 'sung', 'sunk', 'sure',
  'surf', 'swam', 'swan', 'swap', 'sway', 'swim', 'tack', 'tail', 'take',
  'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'task', 'taut', 'teak',
  'teal', 'team', 'tear', 'tech', 'teem', 'tell', 'tend', 'tent', 'term',
  'test', 'text', 'than', 'that', 'thaw', 'thee', 'them', 'then', 'they',
  'thin', 'this', 'thud', 'thus', 'tick', 'tide', 'tidy', 'tier', 'tile',
  'till', 'tilt', 'time', 'tint', 'tiny', 'tire', 'toad', 'toil', 'told',
  'toll', 'tomb', 'tone', 'took', 'tool', 'toot', 'torn', 'toss', 'tour',
  'town', 'trap', 'tray', 'tree', 'trek', 'trim', 'trio', 'trip', 'trot',
  'true', 'tuba', 'tube', 'tuck', 'tuna', 'tune', 'turf', 'turn', 'twig',
  'twin', 'type', 'ugly', 'unit', 'upon', 'urge', 'used', 'user', 'vain',
  'vane', 'vase', 'vast', 'veal', 'veil', 'vein', 'vent', 'verb', 'very',
  'vest', 'veto', 'vibe', 'vice', 'view', 'vine', 'visa', 'void', 'volt',
  'vote', 'wade', 'wage', 'wail', 'wait', 'wake', 'walk', 'wall', 'wand',
  'want', 'ward', 'warm', 'warn', 'warp', 'wart', 'wash', 'wasp', 'wave',
  'wavy', 'weak', 'wean', 'wear', 'weed', 'week', 'weep', 'weld', 'well',
  'went', 'were', 'west', 'what', 'when', 'whip', 'whom', 'wick', 'wide',
  'wife', 'wild', 'will', 'wilt', 'wind', 'wine', 'wing', 'wink', 'wipe',
  'wire', 'wise', 'wish', 'wisp', 'with', 'woke', 'wolf', 'wood', 'wool',
  'word', 'wore', 'work', 'worm', 'worn', 'wove', 'wrap', 'yard', 'yarn',
  'yawn', 'year', 'yell', 'yoga', 'yolk', 'your', 'zeal', 'zero', 'zone',
  'zoom',
];

/** Extra five-letter words, on top of WORDLE_ANSWERS.
 *
 * The crossword fill needs these. Its 5x5 pattern leaves three full rows
 * and a column of five crossing each other, and how many grids exist at all
 * scales steeply with vocabulary: on WORDLE_ANSWERS alone the solver found
 * two in a minute, because nearly every partial fill dead-ends. These are
 * the ordinary words that list happens to exclude — it bars plurals ending
 * in S (a fair rule for a Wordle answer, meaningless for a crossword) and
 * leans away from verb forms. */
export const FIVE_LETTER_EXTRA = [
  'acres', 'actor', 'acute', 'aired', 'alarm', 'album', 'alert', 'alike',
  'amber', 'ample', 'ankle', 'apart', 'apple', 'apron', 'areas', 'armed',
  'aroma', 'ashes', 'aside', 'asked', 'atlas', 'attic', 'bacon', 'badge',
  'bags', 'baked', 'balls', 'bands', 'banks', 'barns', 'based', 'bases',
  'beads', 'beams', 'beans', 'bears', 'beats', 'beers', 'bells', 'belts',
  'bends', 'bikes', 'birds', 'blame', 'blank', 'blast', 'blaze', 'blend',
  'blink', 'blocks', 'bloom', 'blown', 'blues', 'boats', 'bonds', 'bones',
  'books', 'boots', 'bored', 'bowls', 'boxes', 'brain', 'brake', 'brass',
  'brave', 'bread', 'break', 'brick', 'bride', 'brief', 'bring', 'broke',
  'brush', 'bunch', 'burns', 'buses', 'cabin', 'cable', 'cakes', 'calls',
  'calms', 'camel', 'camps', 'candy', 'canoe', 'cards', 'cares', 'carts',
  'carve', 'cases', 'casts', 'catch', 'caves', 'chain', 'chair', 'chalk',
  'charm', 'chase', 'cheap', 'check', 'cheer', 'chess', 'chest', 'chief',
  'child', 'chips', 'chose', 'claim', 'clams', 'clean', 'clear', 'clerk',
  'climb', 'clips', 'clock', 'close', 'cloth', 'cloud', 'clubs', 'coach',
  'coals', 'coast', 'coats', 'coins', 'cooks', 'cools', 'coral', 'cords',
  'costs', 'couch', 'could', 'count', 'court', 'cover', 'crabs', 'crack',
  'craft', 'crane', 'crash', 'crawl', 'cream', 'crept', 'crews', 'crops',
  'cross', 'crowd', 'crown', 'crumb', 'crush', 'cubes', 'cured', 'curls',
  'curve', 'cycle', 'dares', 'dates', 'deals', 'dealt', 'dears', 'decks',
  'deeds', 'deals', 'dense', 'depth', 'desks', 'dimes', 'dines', 'dirty',
  'dishes', 'ditch', 'dived', 'dives', 'docks', 'dolls', 'domes', 'doors',
  'doubt', 'dough', 'doves', 'dozen', 'drags', 'drain', 'drank', 'drawn',
  'draws', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive',
  'drops', 'drove', 'drums', 'ducks', 'dunes', 'dusty', 'eagle', 'early',
  'earns', 'earth', 'eaten', 'edges', 'eight', 'elbow', 'empty', 'ended',
  'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every',
  'exact', 'extra', 'faces', 'facts', 'faded', 'fails', 'faint', 'fairs',
  'faith', 'falls', 'false', 'fancy', 'farms', 'fears', 'feast', 'feeds',
  'feels', 'fence', 'ferry', 'fever', 'field', 'fifth', 'fight', 'files',
  'fills', 'films', 'final', 'finds', 'fines', 'fired', 'fires', 'first',
  'fists', 'flags', 'flame', 'flash', 'fleet', 'flies', 'float', 'flock',
  'flood', 'floor', 'flour', 'flows', 'fluid', 'flute', 'foams', 'folds',
  'folks', 'foods', 'fools', 'force', 'forks', 'forms', 'forth', 'found',
  'frame', 'fresh', 'front', 'frost', 'fruit', 'fumes', 'funds', 'games',
  'gates', 'gazes', 'gears', 'ghost', 'giant', 'gifts', 'girls', 'given',
  'gives', 'glass', 'globe', 'glove', 'glows', 'goals', 'goats', 'going',
  'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grass',
  'grave', 'great', 'green', 'greet', 'grill', 'grins', 'grips', 'group',
  'grown', 'grows', 'guard', 'guess', 'guest', 'guide', 'habit', 'hairs',
  'halls', 'hands', 'hangs', 'happy', 'harsh', 'hatch', 'hates', 'heads',
  'heals', 'heaps', 'heard', 'heart', 'heats', 'heavy', 'hedge', 'heels',
  'helps', 'herbs', 'hides', 'hills', 'hints', 'hired', 'hives', 'holds',
  'holes', 'homes', 'honey', 'hoods', 'hooks', 'hoped', 'hopes', 'horns',
  'horse', 'hoses', 'hotel', 'hours', 'house', 'human', 'hunts', 'hurry',
  'ideal', 'ideas', 'image', 'index', 'inner', 'input', 'irons', 'issue',
  'items', 'jeans', 'jewel', 'joins', 'jokes', 'judge', 'juice', 'jumps',
  'keeps', 'kicks', 'kinds', 'kings', 'kites', 'knees', 'knife', 'knock',
  'knots', 'known', 'knows', 'label', 'lacks', 'lakes', 'lambs', 'lamps',
  'lands', 'lanes', 'large', 'lasts', 'later', 'laugh', 'lawns', 'layer',
  'leads', 'leaks', 'leans', 'leaps', 'learn', 'lease', 'least', 'leave',
  'legal', 'lemon', 'level', 'light', 'limbs', 'limit', 'lines', 'links',
  'lions', 'lists', 'lived', 'lives', 'loads', 'loans', 'local', 'locks',
  'lodge', 'logic', 'looks', 'loops', 'loose', 'lords', 'loses', 'loved',
  'loves', 'lower', 'lucky', 'lunch', 'lungs', 'magic', 'major', 'maker',
  'males', 'maple', 'march', 'marks', 'marsh', 'masks', 'match', 'meals',
  'means', 'meant', 'meats', 'medal', 'meets', 'melts', 'metal', 'meter',
  'might', 'miles', 'mills', 'minds', 'mines', 'minor', 'mixed', 'model',
  'moist', 'moles', 'money', 'month', 'moods', 'moons', 'moral', 'motor',
  'mount', 'mouse', 'mouth', 'moved', 'moves', 'movie', 'music', 'nails',
  'names', 'necks', 'needs', 'nerve', 'nests', 'never', 'newer', 'night',
  'noble', 'noise', 'north', 'notes', 'novel', 'nurse', 'oaths', 'ocean',
  'offer', 'often', 'olive', 'onion', 'opens', 'opera', 'orbit', 'order',
  'organ', 'other', 'otter', 'ounce', 'outer', 'owner', 'packs', 'pages',
  'pails', 'pains', 'paint', 'pairs', 'palms', 'panel', 'panic', 'pants',
  'paper', 'parks', 'parts', 'party', 'paste', 'patch', 'paths', 'pause',
  'peace', 'peach', 'pearl', 'pears', 'pedal', 'peels', 'penny', 'phase',
  'phone', 'photo', 'piano', 'picks', 'piece', 'piles', 'pilot', 'pines',
  'pipes', 'pitch', 'pizza', 'place', 'plain', 'plane', 'plans', 'plant',
  'plate', 'plays', 'plots', 'plugs', 'poems', 'point', 'poles', 'ponds',
  'pools', 'porch', 'ports', 'pound', 'power', 'press', 'price', 'pride',
  'print', 'prize', 'proof', 'proud', 'prove', 'pulls', 'pumps', 'punch',
  'pupil', 'puppy', 'quick', 'quiet', 'quilt', 'quite', 'races', 'racks',
  'radio', 'rails', 'rains', 'raise', 'rally', 'ranch', 'range', 'ranks',
  'rapid', 'rates', 'reach', 'reads', 'ready', 'realm', 'rebel', 'reeds',
  'reefs', 'reels', 'refer', 'relax', 'rents', 'reply', 'rests', 'rider',
  'rides', 'ridge', 'right', 'rings', 'rinks', 'risen', 'rises', 'risks',
  'rival', 'river', 'roads', 'roast', 'robes', 'robin', 'robot', 'rocks',
  'rocky', 'roles', 'rolls', 'roofs', 'rooms', 'roots', 'ropes', 'roses',
  'rough', 'round', 'route', 'royal', 'ruins', 'rules', 'rural', 'sails',
  'saint', 'salad', 'sales', 'sandy', 'sauce', 'scale', 'scarf', 'scene',
  'scent', 'scope', 'score', 'scout', 'seals', 'seams', 'seats', 'seeds',
  'seeks', 'seems', 'sells', 'sends', 'sense', 'serve', 'seven', 'shade',
  'shake', 'shall', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shiny', 'ships', 'shirt', 'shock',
  'shoes', 'shops', 'shore', 'short', 'shots', 'shout', 'shown', 'shows',
  'sides', 'sight', 'signs', 'silly', 'since', 'sings', 'sinks', 'sites',
  'sixth', 'sizes', 'skate', 'skill', 'skins', 'skirt', 'slabs', 'sleep',
  'slept', 'slice', 'slide', 'slope', 'slots', 'small', 'smart', 'smell',
  'smile', 'smoke', 'snack', 'snake', 'snaps', 'solar', 'solid', 'solve',
  'songs', 'sorry', 'sorts', 'sound', 'south', 'space', 'spare', 'spark',
  'speak', 'speed', 'spell', 'spend', 'spent', 'spice', 'spill', 'spine',
  'split', 'spoke', 'spoon', 'sport', 'spots', 'spray', 'squad', 'stack',
  'staff', 'stage', 'stair', 'stake', 'stale', 'stamp', 'stand', 'stare',
  'stars', 'start', 'state', 'stays', 'steam', 'steel', 'steep', 'stems',
  'steps', 'stick', 'stiff', 'still', 'stock', 'stone', 'stood', 'stool',
  'stops', 'store', 'storm', 'story', 'stove', 'strap', 'straw', 'strip',
  'stuck', 'study', 'stuff', 'style', 'sugar', 'suits', 'sunny', 'super',
  'sweet', 'swept', 'swift', 'swims', 'swing', 'table', 'tails', 'taken',
  'takes', 'tales', 'talks', 'tanks', 'tapes', 'tasks', 'taste', 'tasty',
  'teach', 'teams', 'tears', 'teeth', 'tells', 'tends', 'tents', 'terms',
  'tests', 'thank', 'their', 'theme', 'there', 'these', 'thick', 'thief',
  'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw', 'throw',
  'thumb', 'tides', 'tiger', 'tight', 'tiles', 'timer', 'times', 'tired',
  'title', 'toast', 'today', 'token', 'tones', 'tools', 'tooth', 'topic',
  'torch', 'total', 'touch', 'tough', 'tours', 'towel', 'tower', 'towns',
  'trace', 'track', 'trade', 'trail', 'train', 'traps', 'trash', 'trays',
  'treat', 'trees', 'trend', 'trial', 'tribe', 'trick', 'tried', 'trips',
  'truck', 'trunk', 'trust', 'truth', 'tubes', 'tulip', 'tunes', 'turns',
  'twice', 'twigs', 'twins', 'twist', 'uncle', 'under', 'union', 'unite',
  'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'value', 'vault',
  'veins', 'verbs', 'video', 'views', 'vines', 'virus', 'visit', 'vital',
  'vivid', 'vocal', 'voice', 'votes', 'vowel', 'wagon', 'waist', 'waits',
  'wakes', 'walks', 'walls', 'wants', 'wards', 'warms', 'warns', 'waste',
  'watch', 'water', 'waves', 'weeds', 'weeks', 'weigh', 'weird', 'wells',
  'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'winds', 'wines', 'wings', 'wipes', 'wires', 'witch', 'woman',
  'woods', 'words', 'works', 'world', 'worms', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrist', 'write', 'wrong', 'wrote', 'yacht',
  'yards', 'yarns', 'years', 'yield', 'young', 'youth', 'zebra', 'zones',
];

/** Six- and seven-letter words that make good Word Bloom bases: common
 * enough to recognise, and with a letter mix that yields a decent haul of
 * shorter words. */
export const BLOOM_BASES = [
  'animal', 'basket', 'branch', 'bottle', 'camera', 'candle', 'carpet',
  'castle', 'cellar', 'circle', 'closet', 'coffee', 'colour', 'corner',
  'cotton', 'crayon', 'dinner', 'dragon', 'engine', 'family', 'farmer',
  'father', 'finger', 'flower', 'forest', 'friend', 'garden', 'guitar',
  'hamster', 'harvest', 'insect', 'island', 'jacket', 'jungle', 'kitten',
  'ladder', 'lantern', 'listen', 'market', 'meadow', 'monster', 'morning',
  'mother', 'napkin', 'orange', 'packet', 'pantry', 'parcel', 'parent',
  'pencil', 'picnic', 'pirate', 'planet', 'pocket', 'pumpkin', 'puppet',
  'rabbit', 'rocket', 'sailor', 'saddle', 'school', 'silver', 'singer',
  'sister', 'skater', 'spider', 'spring', 'stable', 'summer', 'sunset',
  'temple', 'tiger', 'travel', 'tunnel', 'turtle', 'valley', 'violet',
  'wagon', 'walnut', 'wander', 'window', 'winter', 'wizard', 'yellow',
];

/** Six- and seven-letter words, for Word Bloom's longer bases and the
 * anagram pairs that make its best moment work (GARDEN <-> DANGER,
 * SILENT <-> LISTEN, and a plural base's own singular, PLANETS -> PLANET).
 * Sourced from a common-English frequency list, then vetted by a model
 * against the same bar as the rest of this file ("would a 10-15 year old
 * in this family know it?") to strip the web-corpus noise a frequency
 * list carries on its own — place names, brands, internet/business jargon,
 * abbreviations. Not used for the 3-5 letter packs above; only Word
 * Bloom's vocabulary sweep (buildWordPuzzles.ts) draws on these. */
export const SIX_LETTER = [
  'abroad', 'absent', 'accent', 'accept', 'access', 'across', 'acting', 'action',
  'active', 'actors', 'actual', 'adding', 'adjust', 'adults', 'advice', 'advise',
  'aerial', 'affair', 'affect', 'afford', 'afraid', 'agency', 'agenda', 'agents',
  'agreed', 'agrees', 'albums', 'allows', 'almost', 'always', 'amount', 'anchor',
  'angels', 'animal', 'annual', 'answer', 'anyone', 'anyway', 'appeal', 'appear',
  'arcade', 'argued', 'around', 'arrest', 'arrive', 'artist', 'asking', 'aspect',
  'assist', 'assume', 'asthma', 'atomic', 'attach', 'attack', 'attend', 'august',
  'aurora', 'author', 'autumn', 'avenue', 'awards', 'babies', 'backed', 'baking',
  'ballet', 'ballot', 'banana', 'banned', 'banner', 'barely', 'barrel', 'basics',
  'basket', 'battle', 'beauty', 'beaver', 'became', 'become', 'before', 'begins',
  'behalf', 'behind', 'beings', 'belief', 'belong', 'beside', 'better', 'beyond',
  'bidder', 'bigger', 'bikini', 'bishop', 'blades', 'blocks', 'blonde', 'boards',
  'bodies', 'border', 'boring', 'bother', 'bottle', 'bottom', 'bought', 'boxing',
  'brakes', 'branch', 'breach', 'breaks', 'breast', 'breath', 'breeds', 'bridal',
  'bridge', 'briefs', 'bright', 'brings', 'broken', 'bronze', 'bubble', 'builds',
  'bullet', 'bumper', 'bundle', 'burden', 'buried', 'burner', 'butter', 'button',
  'buyers', 'buying', 'cables', 'called', 'camera', 'campus', 'cancel', 'cancer',
  'candle', 'cannon', 'canvas', 'canyon', 'carbon', 'career', 'caring', 'carpet',
  'castle', 'casual', 'cattle', 'caught', 'caused', 'causes', 'cement', 'center',
  'centre', 'chains', 'chairs', 'chance', 'change', 'chapel', 'charge', 'charms',
  'charts', 'cheats', 'checks', 'cheers', 'cheese', 'cherry', 'choice', 'choose',
  'chorus', 'chosen', 'chubby', 'church', 'cinema', 'circle', 'circus', 'cities',
  'clocks', 'closed', 'closer', 'closes', 'clouds', 'cloudy', 'coffee', 'collar',
  'colony', 'colors', 'colour', 'column', 'combat', 'comedy', 'comics', 'coming',
  'common', 'cooked', 'cookie', 'cooler', 'copied', 'copies', 'copper', 'corner',
  'cotton', 'counts', 'couple', 'coupon', 'course', 'covers', 'cowboy', 'cradle',
  'crafts', 'create', 'credit', 'crimes', 'crisis', 'cruise', 'curves', 'cycles',
  'damage', 'danger', 'dating', 'deadly', 'deaths', 'debate', 'decade', 'decent',
  'decide', 'deemed', 'deeper', 'deeply', 'defeat', 'defend', 'degree', 'delays',
  'demand', 'denial', 'denied', 'desert', 'design', 'desire', 'detail', 'detect',
  'device', 'diesel', 'differ', 'digest', 'dining', 'dinner', 'direct', 'dishes',
  'divide', 'divine', 'diving', 'doctor', 'dollar', 'donate', 'double', 'dozens',
  'dragon', 'dreams', 'drinks', 'driven', 'driver', 'drives', 'during', 'duties',
  'eagles', 'earned', 'easier', 'easily', 'easter', 'eating', 'edited', 'effect',
  'effort', 'either', 'eleven', 'emails', 'empire', 'ending', 'energy', 'engine',
  'enough', 'enters', 'entire', 'errors', 'escape', 'essays', 'events', 'exceed',
  'except', 'excess', 'excuse', 'exists', 'exotic', 'expand', 'expect', 'extend',
  'extent', 'extras', 'fabric', 'facial', 'facing', 'factor', 'failed', 'fairly',
  'fallen', 'family', 'famous', 'farmer', 'faster', 'father', 'favors', 'favour',
  'fellow', 'female', 'fields', 'figure', 'filled', 'filter', 'finals', 'finest',
  'finger', 'finish', 'fitted', 'flavor', 'fleece', 'flight', 'floors', 'floppy',
  'floral', 'flower', 'flying', 'folder', 'follow', 'forced', 'forces', 'forest',
  'forget', 'forgot', 'fossil', 'fought', 'fourth', 'framed', 'frames', 'freely',
  'freeze', 'fridge', 'friend', 'frozen', 'fruits', 'future', 'gained', 'galaxy',
  'gaming', 'garage', 'garden', 'garlic', 'gather', 'gender', 'genius', 'genres',
  'gentle', 'gently', 'giants', 'giving', 'glance', 'gloves', 'golden', 'gospel',
  'gossip', 'gothic', 'gotten', 'grades', 'granny', 'graphs', 'groove', 'ground',
  'groups', 'growth', 'guards', 'guests', 'guided', 'guides', 'guilty', 'guitar',
  'habits', 'hacker', 'hammer', 'handed', 'handle', 'happen', 'harbor', 'harder',
  'hardly', 'having', 'hazard', 'headed', 'health', 'hearts', 'heated', 'heater',
  'heaven', 'height', 'helmet', 'helped', 'herbal', 'heroes', 'hidden', 'higher',
  'highly', 'hiking', 'hockey', 'holder', 'hollow', 'honest', 'honors', 'hoping',
  'horror', 'horses', 'hostel', 'hotels', 'hourly', 'houses', 'humans', 'hunger',
  'hungry', 'hunter', 'hybrid', 'ignore', 'images', 'immune', 'impact', 'impose',
  'inches', 'income', 'indeed', 'indoor', 'infant', 'inform', 'injury', 'insert',
  'inside', 'intake', 'intend', 'invest', 'invite', 'island', 'issues', 'italic',
  'itself', 'jacket', 'jersey', 'joined', 'judges', 'jungle', 'junior', 'kidney',
  'killed', 'killer', 'knight', 'knives', 'labels', 'labour', 'ladder', 'ladies',
  'laptop', 'larger', 'lately', 'latest', 'latter', 'launch', 'lawyer', 'layers',
  'layout', 'leader', 'league', 'leaves', 'legacy', 'legend', 'length', 'lenses',
  'lesser', 'lesson', 'letter', 'levels', 'lights', 'likely', 'limits', 'linear',
  'liquid', 'listed', 'listen', 'little', 'living', 'loaded', 'locate', 'locked',
  'lonely', 'longer', 'losing', 'losses', 'lounge', 'lovely', 'lovers', 'loving',
  'lowest', 'luxury', 'lyrics', 'magnet', 'maiden', 'mailed', 'mainly', 'makers',
  'makeup', 'making', 'manage', 'manner', 'manual', 'marble', 'margin', 'marina',
  'marine', 'marked', 'marker', 'market', 'marvel', 'master', 'mating', 'matrix',
  'matter', 'mature', 'median', 'medium', 'member', 'memory', 'mental', 'mentor',
  'merely', 'metals', 'meters', 'method', 'metres', 'metric', 'middle', 'mighty',
  'mining', 'minute', 'mirror', 'missed', 'mixing', 'mobile', 'models', 'modern',
  'modify', 'moment', 'monkey', 'months', 'mostly', 'motels', 'mother', 'motion',
  'motors', 'mounts', 'movers', 'movies', 'moving', 'murder', 'muscle', 'museum',
  'muslim', 'mutual', 'myself', 'namely', 'narrow', 'nation', 'native', 'nature',
  'nearby', 'nearly', 'needed', 'needle', 'nested', 'newest', 'nickel', 'nights',
  'nobody', 'normal', 'notice', 'notify', 'notion', 'novels', 'number', 'nurses',
  'object', 'obtain', 'occurs', 'offers', 'office', 'offset', 'oldest', 'opened',
  'optics', 'option', 'orange', 'orders', 'origin', 'others', 'outlet', 'output',
  'owners', 'oxygen', 'packed', 'packet', 'palace', 'panels', 'papers', 'parade',
  'parcel', 'parent', 'parish', 'partly', 'passed', 'passes', 'pastor', 'patrol',
  'payday', 'paying', 'peeing', 'pencil', 'people', 'pepper', 'period', 'permit',
  'person', 'phases', 'phones', 'photos', 'phrase', 'picked', 'pickup', 'picnic',
  'pieces', 'pierce', 'pillow', 'pixels', 'placed', 'places', 'plains', 'planes',
  'planet', 'plants', 'plasma', 'plates', 'played', 'player', 'please', 'pledge',
  'plenty', 'pocket', 'poetry', 'points', 'poison', 'police', 'policy', 'polish',
  'portal', 'posing', 'postal', 'posted', 'poster', 'potato', 'pounds', 'powder',
  'powers', 'praise', 'prayer', 'prefer', 'prefix', 'pretty', 'priced', 'prices',
  'priest', 'prince', 'prints', 'prison', 'prizes', 'profit', 'prompt', 'proper',
  'proved', 'proven', 'public', 'pulled', 'pupils', 'purple', 'pursue', 'pushed',
  'puzzle', 'python', 'rabbit', 'racial', 'racing', 'radios', 'radius', 'raised',
  'raises', 'random', 'ranges', 'rapids', 'rarely', 'rather', 'rating', 'ratios',
  'reader', 'really', 'reason', 'recall', 'recent', 'recipe', 'record', 'reduce',
  'refers', 'refine', 'reform', 'refund', 'refuse', 'regard', 'reggae', 'region',
  'reject', 'relate', 'relief', 'remain', 'remark', 'remedy', 'remind', 'remote',
  'remove', 'rental', 'repair', 'repeat', 'report', 'rescue', 'resist', 'resort',
  'result', 'resume', 'return', 'reveal', 'review', 'reward', 'rhythm', 'ribbon',
  'riders', 'riding', 'rivers', 'robots', 'rocket', 'rolled', 'roller', 'roster',
  'rounds', 'routes', 'rubber', 'runner', 'sacred', 'safari', 'safely', 'safety',
  'saints', 'salary', 'salmon', 'sample', 'saturn', 'savage', 'saving', 'saying',
  'scales', 'scared', 'scenes', 'scenic', 'scheme', 'school', 'scored', 'scores',
  'screen', 'script', 'scroll', 'sealed', 'search', 'season', 'second', 'secret',
  'secure', 'seeing', 'seeker', 'seemed', 'select', 'seller', 'sender', 'senior',
  'series', 'settle', 'severe', 'sewing', 'sexual', 'shades', 'shadow', 'shaped',
  'shapes', 'shared', 'shares', 'shaved', 'sheets', 'shield', 'shirts', 'shorts',
  'should', 'showed', 'shower', 'signal', 'signed', 'silent', 'silver', 'simple',
  'simply', 'singer', 'single', 'sister', 'skiing', 'skills', 'skirts', 'sleeps',
  'sleeve', 'slides', 'slight', 'slowly', 'smooth', 'soccer', 'social', 'socket',
  'sodium', 'solely', 'solved', 'sorted', 'sought', 'sounds', 'source', 'spaces',
  'speaks', 'spears', 'speech', 'speeds', 'sphere', 'spider', 'spirit', 'spoken',
  'sports', 'spouse', 'spread', 'spring', 'sprint', 'square', 'stable', 'stages',
  'stamps', 'stands', 'starts', 'stated', 'states', 'static', 'status', 'stayed',
  'steady', 'stereo', 'sticks', 'sticky', 'stocks', 'stolen', 'stones', 'stored',
  'stores', 'strain', 'strand', 'stream', 'street', 'stress', 'strict', 'strike',
  'string', 'strips', 'stroke', 'strong', 'struck', 'studio', 'stupid', 'styles',
  'submit', 'subtle', 'sudden', 'suffer', 'suited', 'summer', 'summit', 'sunset',
  'superb', 'supply', 'surely', 'survey', 'switch', 'symbol', 'system', 'tables',
  'tablet', 'tackle', 'tagged', 'taking', 'talent', 'talked', 'target', 'tattoo',
  'taught', 'techno', 'temple', 'tender', 'tennis', 'terror', 'tested', 'thanks',
  'themes', 'theory', 'things', 'thinks', 'thirty', 'thongs', 'though', 'thread',
  'threat', 'throat', 'thrown', 'throws', 'thumbs', 'ticket', 'tigers', 'timber',
  'timely', 'timing', 'tissue', 'titled', 'titles', 'toilet', 'tomato', 'tongue',
  'topics', 'totals', 'toward', 'towers', 'tracks', 'trades', 'trails', 'trains',
  'trance', 'trauma', 'travel', 'treaty', 'trends', 'trials', 'tribal', 'tribes',
  'tricks', 'triple', 'trivia', 'troops', 'trucks', 'trusts', 'trying', 'tuning',
  'tunnel', 'turned', 'turtle', 'twelve', 'twenty', 'typing', 'unable', 'unique',
  'unless', 'unlike', 'unlock', 'unwrap', 'update', 'urgent', 'useful', 'vacuum',
  'valley', 'valued', 'values', 'valves', 'varied', 'varies', 'velvet', 'verbal',
  'versus', 'vessel', 'victim', 'victor', 'videos', 'viewed', 'viewer', 'violin',
  'virtue', 'vision', 'visits', 'visual', 'vocals', 'voices', 'volume', 'voting',
  'walked', 'wallet', 'walnut', 'wanted', 'warned', 'washer', 'waters', 'wealth',
  'weapon', 'weekly', 'weight', 'wheels', 'wicked', 'widely', 'willow', 'window',
  'winner', 'winter', 'wiring', 'wisdom', 'wishes', 'within', 'wizard', 'wonder',
  'wooden', 'worked', 'worker', 'worlds', 'worthy', 'writer', 'writes', 'yearly',
  'yellow',
];

export const SEVEN_LETTER = [
  'ability', 'absence', 'academy', 'accepts', 'account', 'accused', 'achieve', 'acquire',
  'acrobat', 'acrylic', 'actions', 'actress', 'adapted', 'address', 'adopted', 'advance',
  'advised', 'affairs', 'affects', 'african', 'against', 'airfare', 'airline', 'airport',
  'alcohol', 'algebra', 'alleged', 'allergy', 'allowed', 'already', 'altered', 'amateur',
  'amazing', 'amongst', 'amounts', 'analyze', 'anatomy', 'ancient', 'animals', 'another',
  'answers', 'antenna', 'antique', 'anxiety', 'anybody', 'anymore', 'anytime', 'appears',
  'applied', 'applies', 'approve', 'aquatic', 'arising', 'arrange', 'arrival', 'arrived',
  'arrives', 'article', 'artists', 'artwork', 'aspects', 'assault', 'assists', 'assumed',
  'assumes', 'attacks', 'attempt', 'attract', 'auction', 'authors', 'average', 'awarded',
  'awesome', 'backing', 'balance', 'balloon', 'banners', 'bargain', 'barrier', 'baskets',
  'battery', 'beaches', 'bearing', 'because', 'becomes', 'bedding', 'bedroom', 'beliefs',
  'believe', 'belongs', 'beneath', 'benefit', 'besides', 'between', 'bicycle', 'biggest',
  'billion', 'biology', 'bizarre', 'blanket', 'blessed', 'blocked', 'blowing', 'boating',
  'booking', 'borders', 'bottles', 'bouquet', 'bowling', 'bracket', 'bridges', 'briefly',
  'broader', 'brother', 'brought', 'budgets', 'builder', 'burning', 'buttons', 'cabinet',
  'calcium', 'calling', 'cameras', 'camping', 'candles', 'capable', 'capital', 'captain',
  'capture', 'careers', 'careful', 'carried', 'carrier', 'carries', 'cartoon', 'casting',
  'catalog', 'causing', 'caution', 'ceiling', 'centers', 'central', 'centres', 'century',
  'ceramic', 'certain', 'chamber', 'chances', 'changed', 'changes', 'channel', 'chapter',
  'charged', 'charger', 'charges', 'charity', 'cheaper', 'checked', 'chicken', 'chinese',
  'choices', 'circles', 'circuit', 'citizen', 'claimed', 'clarity', 'classes', 'classic',
  'cleaner', 'cleanup', 'cleared', 'clearly', 'climate', 'clinics', 'closely', 'closest',
  'closing', 'closure', 'clothes', 'cluster', 'coaches', 'coastal', 'coating', 'collect',
  'college', 'cologne', 'colored', 'colours', 'columns', 'combine', 'comfort', 'command',
  'comment', 'compact', 'company', 'compare', 'compete', 'complex', 'concept', 'concern',
  'concert', 'conduct', 'confirm', 'connect', 'consent', 'consist', 'console', 'consult',
  'contact', 'contain', 'content', 'contest', 'context', 'control', 'convert', 'cooking',
  'cooling', 'copying', 'corners', 'correct', 'costume', 'cottage', 'council', 'counted',
  'counter', 'country', 'couples', 'courage', 'courses', 'covered', 'created', 'creates',
  'credits', 'cricket', 'crucial', 'cruises', 'crystal', 'culture', 'curious', 'current',
  'customs', 'cutting', 'cycling', 'damaged', 'damages', 'dancing', 'decades', 'decided',
  'decimal', 'declare', 'decline', 'defects', 'defence', 'defense', 'defined', 'defines',
  'degrees', 'delayed', 'delight', 'deliver', 'demands', 'depends', 'deserve', 'designs',
  'desired', 'despite', 'destiny', 'destroy', 'details', 'develop', 'devices', 'devoted',
  'diagram', 'diamond', 'digital', 'diploma', 'discuss', 'disease', 'display', 'dispute',
  'distant', 'divided', 'doctors', 'dollars', 'drawing', 'dressed', 'dresses', 'drivers',
  'driving', 'dropped', 'durable', 'dynamic', 'earlier', 'earning', 'eastern', 'eclipse',
  'editing', 'effects', 'efforts', 'elderly', 'elected', 'elegant', 'element', 'emerald',
  'emperor', 'endless', 'enemies', 'engaged', 'engines', 'enjoyed', 'enlarge', 'entered',
  'entries', 'episode', 'equally', 'essence', 'eternal', 'evening', 'evident', 'exactly',
  'examine', 'example', 'excited', 'exhaust', 'exhibit', 'existed', 'expects', 'explain',
  'explore', 'express', 'extends', 'extreme', 'fabrics', 'factors', 'factory', 'failing',
  'failure', 'falling', 'fantasy', 'farmers', 'farming', 'fashion', 'fastest', 'fathers',
  'feature', 'feeding', 'feeling', 'females', 'fiction', 'fifteen', 'fighter', 'figured',
  'figures', 'filling', 'fingers', 'fishing', 'fitness', 'fitting', 'flowers', 'focused',
  'folding', 'follows', 'footage', 'foreign', 'forests', 'forever', 'forming', 'formula',
  'fortune', 'forward', 'freedom', 'freight', 'friends', 'funeral', 'further', 'gadgets',
  'gallery', 'garbage', 'gardens', 'general', 'generic', 'genetic', 'genuine', 'geology',
  'getting', 'glasses', 'grammar', 'granted', 'gravity', 'greatly', 'grocery', 'grounds',
  'growing', 'guitars', 'habitat', 'handled', 'handles', 'hanging', 'happens', 'harbour',
  'harmful', 'harmony', 'harvest', 'hazards', 'heading', 'headset', 'healing', 'healthy',
  'hearing', 'heating', 'heavily', 'heights', 'helpful', 'helping', 'herself', 'highest',
  'highway', 'himself', 'history', 'hitting', 'hobbies', 'holders', 'holding', 'holiday',
  'horizon', 'hormone', 'hottest', 'housing', 'however', 'hundred', 'hunting', 'husband',
  'hygiene', 'ignored', 'illegal', 'illness', 'imagine', 'impacts', 'implied', 'implies',
  'improve', 'include', 'infants', 'initial', 'injured', 'inquire', 'inquiry', 'insects',
  'insight', 'install', 'instant', 'instead', 'insulin', 'intense', 'invalid', 'invited',
  'involve', 'islands', 'jackets', 'jewelry', 'joining', 'journal', 'journey', 'jumping',
  'justice', 'justify', 'karaoke', 'keeping', 'killing', 'kingdom', 'kissing', 'kitchen',
  'knowing', 'labeled', 'landing', 'largely', 'largest', 'lasting', 'laundry', 'leaders',
  'leading', 'learned', 'leather', 'leaving', 'lecture', 'legends', 'leisure', 'lessons',
  'letters', 'letting', 'liberty', 'library', 'license', 'licking', 'lighter', 'limited',
  'loading', 'located', 'locking', 'logical', 'longest', 'looking', 'luggage', 'machine',
  'madness', 'magical', 'mailman', 'manager', 'markers', 'marking', 'married', 'martial',
  'massage', 'massive', 'matched', 'matches', 'matters', 'maximum', 'meaning', 'measure',
  'meeting', 'members', 'mention', 'mercury', 'message', 'methods', 'mileage', 'million',
  'mineral', 'minimal', 'minimum', 'minutes', 'miracle', 'mirrors', 'missile', 'missing',
  'mission', 'mistake', 'mixture', 'mobiles', 'moments', 'monitor', 'monster', 'monthly',
  'morning', 'mothers', 'mounted', 'muscles', 'musical', 'mystery', 'nations', 'natural',
  'naughty', 'nearest', 'neither', 'nervous', 'nothing', 'noticed', 'notices', 'novelty',
  'nowhere', 'nuclear', 'numbers', 'nursery', 'objects', 'observe', 'obvious', 'offense',
  'offered', 'officer', 'olympic', 'opening', 'operate', 'opinion', 'opposed', 'options',
  'ordered', 'organic', 'origins', 'outcome', 'outdoor', 'outlets', 'outline', 'outside',
  'overall', 'package', 'packing', 'painful', 'painted', 'parents', 'parking', 'partial',
  'parties', 'partner', 'passage', 'passing', 'passion', 'passive', 'patches', 'patient',
  'pattern', 'payment', 'penalty', 'pendant', 'penguin', 'peoples', 'percent', 'perfect',
  'perform', 'perfume', 'perhaps', 'periods', 'permits', 'persons', 'phantom', 'phrases',
  'physics', 'picking', 'picture', 'pirates', 'placing', 'planets', 'planned', 'planner',
  'plastic', 'players', 'playing', 'pleased', 'pockets', 'pointed', 'popular', 'portion',
  'possess', 'postage', 'posters', 'pottery', 'poultry', 'poverty', 'powered', 'prairie',
  'prayers', 'precise', 'predict', 'prefers', 'prepaid', 'prepare', 'present', 'pressed',
  'prevent', 'primary', 'printed', 'printer', 'private', 'problem', 'proceed', 'process',
  'produce', 'product', 'profile', 'project', 'promise', 'propose', 'protect', 'protein',
  'protest', 'provide', 'pulling', 'purpose', 'pursuit', 'pushing', 'putting', 'puzzles',
  'quality', 'quantum', 'quarter', 'quickly', 'quizzes', 'radical', 'railway', 'rainbow',
  'raising', 'ranging', 'rapidly', 'ratings', 'reached', 'reaches', 'readers', 'reading',
  'reality', 'realize', 'reasons', 'rebound', 'receipt', 'receive', 'recipes', 'records',
  'recover', 'reduced', 'reduces', 'refined', 'reflect', 'refresh', 'refused', 'regards',
  'regions', 'regular', 'related', 'relates', 'release', 'remains', 'remarks', 'removal',
  'removed', 'renewal', 'repairs', 'replace', 'replica', 'replied', 'replies', 'reports',
  'reprint', 'request', 'require', 'reserve', 'resolve', 'resorts', 'respect', 'respond',
  'restore', 'results', 'resumes', 'retired', 'retreat', 'returns', 'reunion', 'reveals',
  'revenge', 'reverse', 'reviews', 'revised', 'rewards', 'rolling', 'romance', 'roughly',
  'routine', 'royalty', 'running', 'sailing', 'samples', 'satisfy', 'savings', 'scanned',
  'scanner', 'schemes', 'scholar', 'schools', 'science', 'scoring', 'scratch', 'screens',
  'scripts', 'seafood', 'seasons', 'seating', 'seconds', 'secrets', 'section', 'seeking',
  'selling', 'senator', 'sending', 'seniors', 'sensors', 'serious', 'service', 'serving',
  'session', 'setting', 'settled', 'seventh', 'several', 'shadows', 'sharing', 'shelter',
  'sheriff', 'shipped', 'shopper', 'shorter', 'shortly', 'showers', 'showing', 'shuttle',
  'signals', 'signing', 'silence', 'similar', 'singing', 'singles', 'sitting', 'skating',
  'skilled', 'smaller', 'smilies', 'smoking', 'society', 'soldier', 'solving', 'somehow',
  'someone', 'soonest', 'sources', 'speaker', 'special', 'species', 'specify', 'spirits',
  'sponsor', 'springs', 'stadium', 'started', 'starter', 'stating', 'station', 'staying',
  'sticker', 'stomach', 'stopped', 'stories', 'strange', 'streams', 'streets', 'stretch',
  'strikes', 'strings', 'stripes', 'student', 'studied', 'studies', 'studios', 'stuffed',
  'stylish', 'succeed', 'success', 'sucking', 'suggest', 'suicide', 'summary', 'sunrise',
  'support', 'suppose', 'supreme', 'surface', 'surfing', 'surgeon', 'surgery', 'surname',
  'surveys', 'survive', 'suspect', 'swedish', 'symbols', 'systems', 'tablets', 'tactics',
  'talking', 'targets', 'teacher', 'teaches', 'teenage', 'telling', 'tension', 'terrace',
  'terrain', 'testing', 'texture', 'theater', 'theatre', 'therapy', 'thermal', 'thought',
  'threads', 'threats', 'through', 'thunder', 'tickets', 'tobacco', 'toddler', 'tonight',
  'toolbox', 'torture', 'totally', 'touched', 'touring', 'tourism', 'tourist', 'towards',
  'tracked', 'tractor', 'trading', 'traffic', 'tragedy', 'trailer', 'trained', 'trainer',
  'transit', 'travels', 'treated', 'tribute', 'trigger', 'triumph', 'trouble', 'trusted',
  'tsunami', 'tuition', 'turning', 'twisted', 'typical', 'unified', 'uniform', 'unknown',
  'unusual', 'updated', 'updates', 'usually', 'vaccine', 'vampire', 'vanilla', 'variety',
  'various', 'varying', 'vehicle', 'version', 'vessels', 'veteran', 'victims', 'victory',
  'viewers', 'viewing', 'village', 'vintage', 'violent', 'virtual', 'viruses', 'visible',
  'visited', 'visitor', 'vitamin', 'voltage', 'volumes', 'waiting', 'walking', 'wanting',
  'warming', 'warning', 'warrant', 'warrior', 'washing', 'watched', 'watches', 'weapons',
  'wearing', 'weather', 'wedding', 'weekend', 'weights', 'welcome', 'welfare', 'western',
  'whether', 'willing', 'windows', 'winners', 'winning', 'wishing', 'without', 'witness',
  'workers', 'working', 'workout', 'worried', 'worship', 'wrapped', 'writers', 'writing',
  'written', 'younger',
];
